// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
// ignore_for_file: use_key_in_widget_constructors
// ignore_for_file: file_names, camel_case_types
import 'package:flutter/material.dart';

/// 设备管理 (一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全)
class mQRoAjnQnBPage extends StatelessWidget {
  const mQRoAjnQnBPage({super.key});

  @override
  Widget build(BuildContext context) {
return SizedBox(width: 375, height: 667, child: Stack(children: [
  Positioned(left: 0, top: 109, width: 375, height: 40, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 20, right: 20, top: 0, bottom: 0), child: Text('下线后该设备XX账号会被登出, 再次登陆需要身份验证', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFFAAAAAA), height: 1.43), overflow: TextOverflow.visible))),
  Positioned(left: 0, top: 69, width: 375, height: 40, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 20, right: 20, top: 0, bottom: 0), child: Text('在线登陆设备  (3)', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFF777777), height: 1.43), overflow: TextOverflow.visible))),
  Positioned(left: 0, top: 164, width: 375, height: 80, child: Stack(children: [
Positioned(left: 20, top: 0, width: 20, height: 20, child: Icon(IconData(0xEB2B, fontFamily: 'lightIconFont'), size: 20, color: Color(0xFF62B7F4))),
Positioned(left: 0, top: 20, width: 375, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 20, right: 20, top: 0, bottom: 0), child: Text('设备类型:   SEA-AL10', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFFAAAAAA), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 40, width: 375, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 20, right: 20, top: 0, bottom: 0), child: Text('操作地点:  威海(220.09.**.09)', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFFAAAAAA), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 40, top: 0, width: 100, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('nova 5 Pro', textAlign: TextAlign.center, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 140, top: 0, width: 100, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('(当前设备)', textAlign: TextAlign.center, style: TextStyle(fontSize: 14, color: Color(0xFF555555), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 60, width: 375, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 20, right: 20, top: 0, bottom: 0), child: Text('最近登录:  2020-11-19  18:09', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFFAAAAAA), height: 1.43), overflow: TextOverflow.visible)))
])),
  Positioned(left: 0, top: 260, width: 414, height: 100, child: Stack(children: [
Positioned(left: 20, top: 0, width: 20, height: 20, child: Icon(IconData(0xEB07, fontFamily: 'lightIconFont'), size: 20, color: Color(0xFF62B7F4))),
Positioned(left: 0, top: 20, width: 375, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 20, right: 20, top: 0, bottom: 0), child: Text('设备类型:   MI 6', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFFAAAAAA), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 60, width: 375, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 20, right: 20, top: 0, bottom: 0), child: Text('最近登录:  2020-11-19  18:09', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFFAAAAAA), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 80, width: 375, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 20, right: 20, top: 0, bottom: 0), child: Text('超过天未使用', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFFAAAAAA), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 40, top: 0, width: 100, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('小米手机', textAlign: TextAlign.center, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 40, width: 375, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 20, right: 20, top: 0, bottom: 0), child: Text('操作地点:  威海(220.09.**.09)', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFFAAAAAA), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 271, top: 20, width: 80, height: 30, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(3), border: Border.all(color: Color(0xFFF6F7F8), width: 1)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('下线', textAlign: TextAlign.center, style: TextStyle(fontSize: 14, color: Color(0xFF62B7F4), height: 1.43), overflow: TextOverflow.visible)))
])),
  Positioned(left: 0, top: 394, width: 414, height: 100, child: Stack(children: [
Positioned(left: 20, top: 0, width: 20, height: 20, child: Icon(IconData(0xED70, fontFamily: 'lightIconFont'), size: 20, color: Color(0xFF62B7F4))),
Positioned(left: 0, top: 20, width: 375, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 20, right: 20, top: 0, bottom: 0), child: Text('设备类型:   OPPO R11s', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFFAAAAAA), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 60, width: 375, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 20, right: 20, top: 0, bottom: 0), child: Text('最近登录:  2020-11-19  18:09', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFFAAAAAA), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 80, width: 375, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 20, right: 20, top: 0, bottom: 0), child: Text('超过天未使用', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFFAAAAAA), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 40, top: 0, width: 100, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('OPPO R11s', textAlign: TextAlign.center, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 40, width: 375, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 20, right: 20, top: 0, bottom: 0), child: Text('操作地点:  威海(220.09.**.09)', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFFAAAAAA), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 271, top: 20, width: 80, height: 30, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(3), border: Border.all(color: Color(0xFFF6F7F8), width: 1)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('下线', textAlign: TextAlign.center, style: TextStyle(fontSize: 14, color: Color(0xFF62B7F4), height: 1.43), overflow: TextOverflow.visible)))
])),
  Positioned(left: 0, top: 0, width: 375, height: 20, child: Stack(children: [
Positioned(left: 0, top: 0, width: 375, height: 20, child: Stack(children: [
Positioned(left: 0, top: 0, width: 375, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), alignment: Alignment.centerLeft, padding: EdgeInsets.only(left: 6, top: 0, right: 8, bottom: 0))),
Positioned(left: 349, top: 2, width: 16, height: 16, child: Icon(IconData(0xEB08, fontFamily: 'lightIconFont'), size: 16, color: Color(0xFF333333))),
Positioned(left: 45, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E8, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333))),
Positioned(left: 305, top: 6, width: 8, height: 8, child: Icon(IconData(0xEB10, fontFamily: 'lightIconFont'), size: 8, color: Color(0xFF333333))),
Positioned(left: 73, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E7, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333))),
Positioned(left: 6, top: 7, width: 30, height: 5, child: Stack(children: [
Positioned(left: 0, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 6, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 13, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 19, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 25, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1F, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF7F7F7F)))
])),
Positioned(left: 318, top: 5, width: 26, height: 10, child: SizedBox.shrink()),
Positioned(left: 59, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E8, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333)))
]))
])),
  Positioned(left: 0, top: 20, width: 375, height: 44, child: Stack(children: [
Positioned(left: 44, top: 0, width: 287, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('设备管理', textAlign: TextAlign.center, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 0, width: 16, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 16, top: 0, width: 28, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 359, top: 0, width: 16, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 331, top: 0, width: 28, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 14, width: 16, height: 16, child: Icon(IconData(0xE998, fontFamily: 'boldIconFont'), size: 16, color: Color(0xFF000000))),
Positioned(left: 0, top: 0, width: 44, height: 44, child: SizedBox.shrink())
])),
]));
  }
}