// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
// ignore_for_file: use_key_in_widget_constructors
// ignore_for_file: file_names, camel_case_types
import 'package:flutter/material.dart';

/// APP/H5-个人中心 (一账通(IDaaS & IAM)-运营端(SSO)/个人中心)
class sfTDGH3J2yljPage extends StatelessWidget {
  const sfTDGH3J2yljPage({super.key});

  @override
  Widget build(BuildContext context) {
return SizedBox(width: 375, height: 667, child: Stack(children: [
]));
  }
}