// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
// ignore_for_file: use_key_in_widget_constructors
// ignore_for_file: file_names, camel_case_types
import 'package:flutter/material.dart';

/// Google+解除绑定 (一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/账号关联/Google+绑定/解绑)
class YpSMXmVPoGtPage extends StatelessWidget {
  const YpSMXmVPoGtPage({super.key});

  @override
  Widget build(BuildContext context) {
return SizedBox(width: 375, height: 667, child: Stack(children: [
  Positioned(left: 28, top: 236, width: 320, height: 50, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(16)), padding: EdgeInsets.only(left: 0, right: 0, top: 10, bottom: 0), child: Text('解除与XX账号的绑定?', textAlign: TextAlign.center, style: TextStyle(fontSize: 14, color: Color(0xFF777777), height: 1.43), overflow: TextOverflow.visible))),
  Positioned(left: 28, top: 286, width: 320, height: 145, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(16)), padding: EdgeInsets.only(left: 10, right: 10, top: 10, bottom: 0), child: Text('解除绑定后您将无法使用该XX账号登陆XX平台', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFF777777), height: 1.43), overflow: TextOverflow.visible))),
  Positioned(left: 47.2, top: 372.2, width: 120, height: 48, child: Stack(children: [
Positioned.fill(child: Container(decoration: BoxDecoration(color: Color(0xFFF6F7F8), borderRadius: BorderRadius.circular(24)))),
Positioned(left: 46, top: 16, width: 28, height: 16, child: Text('取消', textAlign: TextAlign.left, overflow: TextOverflow.visible))
])),
  Positioned(left: 207.2, top: 372.2, width: 120, height: 48, child: Stack(children: [
Positioned.fill(child: Container(decoration: BoxDecoration(color: Color(0xFF3EB5AE), borderRadius: BorderRadius.circular(24)))),
Positioned(left: 18, top: 16, width: 84, height: 16, child: Text('确认解除绑定', textAlign: TextAlign.left, overflow: TextOverflow.visible))
])),
]));
  }
}