name: ruoqi_flutter_ui
description: RuoQi Flutter monorepo.
publish_to: 'none'

environment:
  sdk: ^3.12.0

workspace:
  - apps/platform_app
  - apps/platform_pc
  - apps/business_app
  - apps/business_pc
  - packages/ruoqi_common
  - packages/ruoqi_network
  - packages/ruoqi_platform_api
  - packages/ruoqi_customer_api
  - packages/ruoqi_merchant_api
  - packages/ruoqi_partner_api

dev_dependencies:
  melos: ^6.3.0
