// Generated by tools/rp2flutter/convert.py — do not edit by hand.
import 'package:flutter/material.dart';
import 'package:ruoqi_common/ruoqi_common.dart';

import 'business/system_manage_page.dart';
import 'prototype_registry.dart';
import 'prototype_viewer.dart';

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    final grouped = <String, List<PrototypeEntry>>{};
    for (final e in prototypePages) {
      grouped.putIfAbsent(e.path.split('/').first, () => []).add(e);
    }
    final keys = grouped.keys.toList()..sort();
    return Scaffold(
      appBar: AppBar(
        title: const Text('RuoQi 平台(App) — 运营端原型页面'),
        actions: const [
          Padding(
            padding: EdgeInsets.only(right: 16),
            child: Center(child: AppBadge(appName: 'platform_app', version: '1.0.0')),
          ),
        ],
      ),
      body: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          Card(
            margin: EdgeInsets.zero,
            color: Theme.of(context).colorScheme.primaryContainer,
            child: ListTile(
              contentPadding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
              leading: Icon(
                Icons.admin_panel_settings,
                size: 36,
                color: Theme.of(context).colorScheme.primary,
              ),
              title: const Text(
                '系统管理',
                style: TextStyle(fontSize: 17, fontWeight: FontWeight.w700),
              ),
              subtitle: const Text('运营端 App 页面（个人中心 / 账号安全等）'),
              trailing: const Icon(Icons.arrow_forward),
              onTap: () {
                Navigator.of(context).push(
                  MaterialPageRoute(builder: (_) => const SystemManagePage()),
                );
              },
            ),
          ),
          const SizedBox(height: 20),
          Text(
            '原型页面（像素级复刻，共 ${prototypePages.length} 页）',
            style: Theme.of(context).textTheme.titleSmall,
          ),
          const SizedBox(height: 4),
          Text(
            '共 ${grouped.length} 个模块、${prototypePages.length} 个页面（来自摹客 RP 原型，自动转换）',
            style: Theme.of(context).textTheme.bodyMedium,
          ),
          const SizedBox(height: 8),
          for (final key in keys) ...[
            ExpansionTile(
              title: Text(key),
              tilePadding: EdgeInsets.zero,
              children: [
                for (final e in grouped[key]!)
                  ListTile(
                    dense: true,
                    leading: const Icon(Icons.description_outlined, size: 18),
                    title: Text(e.title),
                    subtitle: Text(e.path, maxLines: 1, overflow: TextOverflow.ellipsis),
                    onTap: () {
                      Navigator.of(context).push(
                        MaterialPageRoute(
                          builder: (_) => PrototypeViewer(entry: e),
                        ),
                      );
                    },
                  ),
              ],
            ),
          ],
        ],
      ),
    );
  }
}
