// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
import 'package:flutter/material.dart';

import 'pages/sfTDGH3J2ylj.dart';
import 'pages/WbxSZcLPC.dart';
import 'pages/4yKkvNZVxI.dart';
import 'pages/wPmXbzPkiP.dart';
import 'pages/WT2vrChiIM.dart';
import 'pages/jp-JRrwD8ev.dart';
import 'pages/eD8r7ac9Ar.dart';
import 'pages/XWrXd-5DFX.dart';
import 'pages/Q7pSP10kxv.dart';
import 'pages/ktI0qrIKhI.dart';
import 'pages/OPRICs3r8Iy.dart';
import 'pages/stAm2p0caNj.dart';
import 'pages/Xz7-wB4IdeP.dart';
import 'pages/5c07-l8F9j.dart';
import 'pages/rjFXM9IKCo.dart';
import 'pages/Z7lwtme8W2.dart';
import 'pages/9yWGvUbAjQ.dart';
import 'pages/nRYc08H7FPx.dart';
import 'pages/qEf_BDKxNv.dart';
import 'pages/3UU0HSEgeR1.dart';
import 'pages/uu3c0KpW8XX.dart';
import 'pages/lMDpoKb0owo.dart';
import 'pages/DDcWTjd3w2i.dart';
import 'pages/B8DSoghIDjT.dart';
import 'pages/BRu64F0WGgf.dart';
import 'pages/OO00mmKkw7o.dart';
import 'pages/uAluex6xVmn.dart';
import 'pages/m7E6B4--XJe.dart';
import 'pages/5hMRVTSTXzj.dart';
import 'pages/0N31bJu4vhl.dart';
import 'pages/aTrJLpegsRB.dart';
import 'pages/ICynxVG_83S.dart';
import 'pages/nLC1T0IKQLH.dart';
import 'pages/UiSVuLKQSLz.dart';
import 'pages/qOyzrXtNYgj.dart';
import 'pages/4Ige3CEEzeu.dart';
import 'pages/Qrz6QvXNU-.dart';
import 'pages/IjZ4ZIHgE9q.dart';
import 'pages/NGy6CqwixBi.dart';
import 'pages/G9H5L-TOogh.dart';
import 'pages/qGbVZfyHmkA.dart';
import 'pages/Bku-V30Tj-O.dart';
import 'pages/htYkt4s28SJ.dart';
import 'pages/WvpLTmnlIDQ.dart';
import 'pages/re2aLsg3sLY.dart';
import 'pages/YpSMXmVPoGt.dart';
import 'pages/FO-5lAkM4rf.dart';
import 'pages/WBGNjlD-jq0.dart';
import 'pages/8G-KBHzomp-.dart';
import 'pages/mQR-oAjnQnB.dart';
import 'pages/HgsWg8kG_al.dart';
import 'pages/Q2wLEtWfRC4.dart';

class PrototypeFolder {
  const PrototypeFolder(this.name, this.children);
  final String name;
  final List<Object> children;
}

class PrototypeEntry {
  const PrototypeEntry(this.id, this.title, this.path, this.width, this.height, this.builder);
  final String id;
  final String title;
  final String path;
  final double width;
  final double height;
  final WidgetBuilder builder;
}

final List<PrototypeEntry> prototypePages = [
  PrototypeEntry('4yKkvNZVxI', '个人资料 (已绑定)-普通用户', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/个人资料 (已绑定)-普通用户', 375, 1000, (_) => P4yKkvNZVxIPage()),
  PrototypeEntry('9yWGvUbAjQ', '账号安全', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全', 375, 667, (_) => P9yWGvUbAjQPage()),
  PrototypeEntry('Q7pSP10kxv', '头像修改', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/头像修改', 375, 667, (_) => Q7pSP10kxvPage()),
  PrototypeEntry('WT2vrChiIM', '个人资料-企业用户', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/个人资料-企业用户', 375, 1000, (_) => WT2vrChiIMPage()),
  PrototypeEntry('XWrXd-5DFX', '年龄修改/设置', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/年龄修改/设置', 375, 667, (_) => XWrXd5DFXPage()),
  PrototypeEntry('eD8r7ac9Ar', '性别修改/设置', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/性别修改/设置', 375, 667, (_) => eD8r7ac9ArPage()),
  PrototypeEntry('ktI0qrIKhI', '修改昵称', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/修改昵称', 375, 667, (_) => ktI0qrIKhIPage()),
  PrototypeEntry('jp-JRrwD8ev', '个人资料-企业用户 (1)', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/个人资料-企业用户/个人资料-企业用户 (1)', 375, 1000, (_) => jpJRrwD8evPage()),
  PrototypeEntry('wPmXbzPkiP', '个人资料(未绑定)', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/个人资料 (已绑定)-普通用户/个人资料(未绑定)', 375, 1000, (_) => wPmXbzPkiPPage()),
  PrototypeEntry('OPRICs3r8Iy', '手机号绑定', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/手机号绑定/手机号绑定', 375, 667, (_) => OPRICs3r8IyPage()),
  PrototypeEntry('Xz7-wB4IdeP', '手机号绑定成功页面', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/手机号绑定/手机号绑定/手机号绑定成功页面', 375, 667, (_) => Xz7wB4IdePPage()),
  PrototypeEntry('stAm2p0caNj', '输入验证码', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/手机号绑定/手机号绑定/输入验证码', 375, 667, (_) => stAm2p0caNjPage()),
  PrototypeEntry('G9H5L-TOogh', '账号关联', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/账号关联', 375, 667, (_) => G9H5LTOoghPage()),
  PrototypeEntry('HgsWg8kG_al', '账号日志', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/账号日志', 375, 667, (_) => HgsWg8kGalPage()),
  PrototypeEntry('mQR-oAjnQnB', '设备管理', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/设备管理', 375, 667, (_) => mQRoAjnQnBPage()),
  PrototypeEntry('3UU0HSEgeR1', '修改密码（旧密码）', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/密码/修改密码（旧密码）', 375, 667, (_) => P3UU0HSEgeR1Page()),
  PrototypeEntry('BRu64F0WGgf', '密码修改成功', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/密码/密码修改成功', 375, 667, (_) => BRu64F0WGgfPage()),
  PrototypeEntry('lMDpoKb0owo', '选择验证方式(修改密码)', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/密码/选择验证方式(修改密码)', 375, 667, (_) => lMDpoKb0owoPage()),
  PrototypeEntry('nRYc08H7FPx', '新设置密码', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/密码/新设置密码', 375, 667, (_) => nRYc08H7FPxPage()),
  PrototypeEntry('uu3c0KpW8XX', '确认新密码', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/密码/修改密码（旧密码）/确认新密码', 375, 667, (_) => uu3c0KpW8XXPage()),
  PrototypeEntry('qEf_BDKxNv_', '密码设置成功', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/密码/新设置密码/密码设置成功', 375, 667, (_) => qEfBDKxNvPage()),
  PrototypeEntry('B8DSoghIDjT', '邮箱验证', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/密码/选择验证方式(修改密码)/邮箱验证', 375, 667, (_) => B8DSoghIDjTPage()),
  PrototypeEntry('DDcWTjd3w2i', '手机短信验证', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/密码/选择验证方式(修改密码)/手机短信验证', 375, 667, (_) => DDcWTjd3w2iPage()),
  PrototypeEntry('OO00mmKkw7o', '新绑定手机号', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/手机号/新绑定手机号', 375, 667, (_) => OO00mmKkw7oPage()),
  PrototypeEntry('m7E6B4--XJe', '修改手机号', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/手机号/修改手机号', 375, 667, (_) => m7E6B4XJePage()),
  PrototypeEntry('5hMRVTSTXzj', '选择验证方式(修改手机号)', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/手机号/修改手机号/选择验证方式(修改手机号)', 375, 667, (_) => P5hMRVTSTXzjPage()),
  PrototypeEntry('ICynxVG_83S', '手机号修改成功', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/手机号/修改手机号/手机号修改成功', 375, 667, (_) => ICynxVG83SPage()),
  PrototypeEntry('0N31bJu4vhl', '手机短信验证  (修改手机号)', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/手机号/修改手机号/选择验证方式(修改手机号)/手机短信验证  (修改手机号)', 375, 667, (_) => P0N31bJu4vhlPage()),
  PrototypeEntry('aTrJLpegsRB', '邮箱验证 (修改手机号)', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/手机号/修改手机号/选择验证方式(修改手机号)/邮箱验证 (修改手机号)', 375, 667, (_) => aTrJLpegsRBPage()),
  PrototypeEntry('uAluex6xVmn', '手机号绑定成功', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/手机号/新绑定手机号/手机号绑定成功', 375, 667, (_) => uAluex6xVmnPage()),
  PrototypeEntry('Bku-V30Tj-O', 'Apple绑定成功页面', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/账号关联/Apple账号绑定/解绑/Apple添加绑定/Apple绑定成功页面', 375, 667, (_) => BkuV30TjOPage()),
  PrototypeEntry('htYkt4s28SJ', 'Apple解除绑定', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/账号关联/Apple账号绑定/解绑/Apple解除绑定', 375, 667, (_) => htYkt4s28SJPage()),
  PrototypeEntry('qGbVZfyHmkA', 'Apple添加绑定', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/账号关联/Apple账号绑定/解绑/Apple添加绑定', 375, 667, (_) => qGbVZfyHmkAPage()),
  PrototypeEntry('8G-KBHzomp-', 'Facebook解除绑定 (1)', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/账号关联/Facebook绑定/解绑/Facebook解除绑定 (1)', 375, 667, (_) => P8GKBHzompPage()),
  PrototypeEntry('FO-5lAkM4rf', 'Facebook添加绑定 (1)', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/账号关联/Facebook绑定/解绑/Facebook添加绑定 (1)', 375, 667, (_) => FO5lAkM4rfPage()),
  PrototypeEntry('WBGNjlD-jq0', '绑定成功页面 (1)', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/账号关联/Facebook绑定/解绑/Facebook添加绑定 (1)/绑定成功页面 (1)', 375, 667, (_) => WBGNjlDjq0Page()),
  PrototypeEntry('re2aLsg3sLY', 'Google+ 绑定成功页面', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/账号关联/Google+绑定/解绑/Google+添加绑定/Google+ 绑定成功页面', 375, 667, (_) => re2aLsg3sLYPage()),
  PrototypeEntry('WvpLTmnlIDQ', 'Google+添加绑定', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/账号关联/Google+绑定/解绑/Google+添加绑定', 375, 667, (_) => WvpLTmnlIDQPage()),
  PrototypeEntry('YpSMXmVPoGt', 'Google+解除绑定', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/账号关联/Google+绑定/解绑/Google+解除绑定', 375, 667, (_) => YpSMXmVPoGtPage()),
  PrototypeEntry('Q2wLEtWfRC4', '账号日志详情', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/账号日志/账号日志详情', 375, 667, (_) => Q2wLEtWfRC4Page()),
  PrototypeEntry('nLC1T0IKQLH', '新绑定邮箱', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/邮箱/新绑定邮箱', 375, 667, (_) => nLC1T0IKQLHPage()),
  PrototypeEntry('qOyzrXtNYgj', '修改邮箱', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/邮箱/修改邮箱', 375, 667, (_) => qOyzrXtNYgjPage()),
  PrototypeEntry('4Ige3CEEzeu', '选择验证方式(修改邮箱)', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/邮箱/修改邮箱/选择验证方式(修改邮箱)', 375, 667, (_) => P4Ige3CEEzeuPage()),
  PrototypeEntry('NGy6CqwixBi', '邮箱修改成功', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/邮箱/修改邮箱/邮箱修改成功', 375, 667, (_) => NGy6CqwixBiPage()),
  PrototypeEntry('IjZ4ZIHgE9q', '邮箱验证 (修改手机号)', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/邮箱/修改邮箱/选择验证方式(修改邮箱)/邮箱验证 (修改手机号)', 375, 667, (_) => IjZ4ZIHgE9qPage()),
  PrototypeEntry('Qrz6QvXNU-_', '手机短信验证 (修改手机号)', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/邮箱/修改邮箱/选择验证方式(修改邮箱)/手机短信验证 (修改手机号)', 375, 667, (_) => Qrz6QvXNUPage()),
  PrototypeEntry('UiSVuLKQSLz', '邮箱绑定成功', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/邮箱/新绑定邮箱/邮箱绑定成功', 375, 667, (_) => UiSVuLKQSLzPage()),
  PrototypeEntry('5c07-l8F9j', '邮箱绑定', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/邮箱绑定/邮箱绑定', 375, 667, (_) => P5c07l8F9jPage()),
  PrototypeEntry('Z7lwtme8W2', '邮箱绑定成功页面', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/邮箱绑定/邮箱绑定/邮箱绑定成功页面', 375, 667, (_) => Z7lwtme8W2Page()),
  PrototypeEntry('rjFXM9IKCo', '输入验证码', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)/邮箱绑定/邮箱绑定/输入验证码', 375, 667, (_) => rjFXM9IKCoPage()),
  PrototypeEntry('WbxSZcLPC', '(APP)用户个人中心 (1)', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心/(APP)用户个人中心 (1)', 375, 667, (_) => WbxSZcLPCPage()),
  PrototypeEntry('sfTDGH3J2ylj', 'APP/H5-个人中心', '一账通(IDaaS & IAM)-运营端(SSO)/个人中心/APP/H5-个人中心', 375, 667, (_) => sfTDGH3J2yljPage()),
];

final Map<String, PrototypeEntry> prototypePageById = {
  for (final e in prototypePages) e.id: e,
};
