// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
// ignore_for_file: use_key_in_widget_constructors
// ignore_for_file: file_names, camel_case_types
import 'package:flutter/material.dart';

/// 本机号码一键验证登入 (租户-APP端/会员端登录(APP))
class P0jISefDdcnPage extends StatelessWidget {
  const P0jISefDdcnPage({super.key});

  @override
  Widget build(BuildContext context) {
return SizedBox(width: 375, height: 667, child: Stack(children: [
  Positioned(left: -955, top: 0, width: 375, height: 813, child: ClipRRect(borderRadius: BorderRadius.circular(0), child: Image.asset('assets/images/13cc9fc0-c60b-11ec-8809-2dc58a628408.png', fit: BoxFit.contain, width: 375, height: 813))),
  Positioned(left: 0, top: 199, width: 375, height: 40, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('150****0728', textAlign: TextAlign.center, style: TextStyle(fontSize: 32, color: Color(0xFF333333), fontWeight: FontWeight.w700, letterSpacing: 3, height: 0.75), overflow: TextOverflow.visible))),
  Positioned(left: 32.3, top: 243, width: 311, height: 18, child: SizedBox.shrink()),
  Positioned(left: 32, top: 314, width: 327, height: 40, child: Stack(children: [
Positioned.fill(child: Container(decoration: BoxDecoration(color: Color(0xFF000000), borderRadius: BorderRadius.circular(24)))),
Positioned(left: 107.5, top: 12, width: 112, height: 16, child: Text('本机号码一键登入', textAlign: TextAlign.left, overflow: TextOverflow.visible))
])),
  Positioned(left: 22, top: 39, width: 20, height: 20, child: Icon(IconData(0xEA5B, fontFamily: 'boldIconFont'), size: 20, color: Color(0xFF333333))),
  Positioned(left: 0.3, top: 0, width: 375, height: 20, child: Stack(children: [
Positioned(left: 0, top: 0, width: 375, height: 20, child: Stack(children: [
Positioned(left: 0, top: 0, width: 375, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), alignment: Alignment.centerLeft, padding: EdgeInsets.only(left: 6, top: 0, right: 8, bottom: 0))),
Positioned(left: 349, top: 2, width: 16, height: 16, child: Icon(IconData(0xEB08, fontFamily: 'lightIconFont'), size: 16, color: Color(0xFF333333))),
Positioned(left: 45, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E8, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333))),
Positioned(left: 305, top: 6, width: 8, height: 8, child: Icon(IconData(0xEB10, fontFamily: 'lightIconFont'), size: 8, color: Color(0xFF333333))),
Positioned(left: 73, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E7, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333))),
Positioned(left: 6, top: 7, width: 30, height: 5, child: Stack(children: [
Positioned(left: 0, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 6, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 13, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 19, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 25, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1F, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF7F7F7F)))
])),
Positioned(left: 318, top: 5, width: 26, height: 10, child: SizedBox.shrink()),
Positioned(left: 59, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E8, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333)))
]))
])),
  Positioned(left: 32.3, top: 160, width: 311, height: 22, child: SizedBox.shrink()),
  Positioned(left: 335, top: 37, width: 24, height: 24, child: Icon(IconData(0xEA91, fontFamily: 'boldIconFont'), size: 24, color: Color(0xFFD7D7D7))),
  Positioned(left: -531.0, top: -0.1, width: 375, height: 813, child: ClipRRect(borderRadius: BorderRadius.circular(0), child: Image.asset('assets/images/e8a24960-c6b6-11ec-a807-7d3271559b2e.png', fit: BoxFit.contain, width: 375, height: 813))),
  Positioned(left: 32, top: 370, width: 310, height: 30, child: Stack(children: [
Positioned(left: 18, top: 0, width: 292, height: 30, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(0), boxShadow: [BoxShadow(color: Color(0x26000000), blurRadius: 0, offset: Offset(0, 0))]), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('已阅读并同意 ', textAlign: TextAlign.left, style: TextStyle(fontSize: 10, color: Color(0xFF7F7F7F), height: 1.20), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 0, width: 23, height: 17, child: Stack(children: [
Positioned.fill(child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(0), border: Border.all(color: Color(0xFF000000), width: 1), boxShadow: [BoxShadow(color: Color(0x26000000), blurRadius: 0, offset: Offset(0, 0))]))),
Positioned(left: 0, top: 2, width: 13, height: 13, child: Stack(children: [
Positioned.fill(child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(100), border: Border.all(color: Color(0xFF777777), width: 1), boxShadow: [BoxShadow(color: Color(0x26000000), blurRadius: 0, offset: Offset(0, 0))]))),
Positioned(left: 3, top: 3, width: 7, height: 7, child: Container(decoration: BoxDecoration(color: Color(0xFF777777), borderRadius: BorderRadius.circular(100), border: Border.all(color: Color(0xFF000000), width: 1), boxShadow: [BoxShadow(color: Color(0x26000000), blurRadius: 0, offset: Offset(0, 0))])))
])),
Positioned(left: 23, top: 0, height: 17, child: SizedBox.shrink())
]))
])),
]));
  }
}