// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
// ignore_for_file: use_key_in_widget_constructors
// ignore_for_file: file_names, camel_case_types
import 'package:flutter/material.dart';

/// 账号关联 (租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全)
class P7tGZvikVXuPage extends StatelessWidget {
  const P7tGZvikVXuPage({super.key});

  @override
  Widget build(BuildContext context) {
return SizedBox(width: 375, height: 667, child: Stack(children: [
  Positioned(left: 24, top: 16, width: 110, height: 34, child: SizedBox.shrink()),
  Positioned(left: 24, top: 50, width: 327, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('绑定的第三方账号可用于授权登录Ehomes账号', textAlign: TextAlign.left, style: TextStyle(fontSize: 12, color: Color(0xFFBFC5CA), height: 1.67), overflow: TextOverflow.visible))),
  Positioned(left: 0, top: 110, width: 375, height: 72, child: Stack(children: [
Positioned(left: 287, top: 0, width: 64, height: 72, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('已绑定', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFFBFC5CA), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 0, width: 24, height: 72, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 85, top: 0, width: 202, height: 72, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('Apple', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF000000), fontWeight: FontWeight.w700, height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 351, top: 0, width: 24, height: 72, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 341, top: 31, width: 10, height: 10, child: Icon(IconData(0xE994, fontFamily: 'boldIconFont'), size: 10, color: Color(0xFFBFC5CA))),
Positioned(left: 25, top: 0, width: 60, height: 72, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 9, width: 54, height: 54, child: Stack(children: [
Positioned(left: 0, top: 0, width: 54, height: 54, child: Container(decoration: BoxDecoration(shape: BoxShape.circle, color: Color(0xFF31333E)))),
Positioned(left: 12, top: 12, width: 30, height: 30, child: Icon(IconData(0xED71, fontFamily: 'lightIconFont'), size: 30, color: Color(0xFFFFFFFF)))
]))
])),
  Positioned(left: 0, top: 198, width: 375, height: 72, child: Stack(children: [
Positioned(left: 287, top: 0, width: 64, height: 72, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('已绑定', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFFBFC5CA), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 0, width: 24, height: 72, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 85, top: 0, width: 202, height: 72, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('Facebook', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF000000), fontWeight: FontWeight.w700, height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 351, top: 0, width: 24, height: 72, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 341, top: 31, width: 10, height: 10, child: Icon(IconData(0xE994, fontFamily: 'boldIconFont'), size: 10, color: Color(0xFFBFC5CA))),
Positioned(left: 25, top: 0, width: 60, height: 72, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 9, width: 54, height: 54, child: Stack(children: [
Positioned(left: 0, top: 0, width: 54, height: 54, child: Container(decoration: BoxDecoration(shape: BoxShape.circle, color: Color(0xFF007EB4)))),
Positioned(left: 12, top: 12, width: 30, height: 30, child: Icon(IconData(0xED60, fontFamily: 'lightIconFont'), size: 30, color: Color(0xFFFFFFFF)))
]))
])),
  Positioned(left: 0, top: 286, width: 375, height: 72, child: Stack(children: [
Positioned(left: 287, top: 0, width: 64, height: 72, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('已绑定', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFFBFC5CA), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 0, width: 24, height: 72, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 85, top: 0, width: 202, height: 72, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('Google+', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF000000), fontWeight: FontWeight.w700, height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 351, top: 0, width: 24, height: 72, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 341, top: 31, width: 10, height: 10, child: Icon(IconData(0xE994, fontFamily: 'boldIconFont'), size: 10, color: Color(0xFFBFC5CA))),
Positioned(left: 25, top: 0, width: 60, height: 72, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 9, width: 54, height: 54, child: Stack(children: [
Positioned(left: 0, top: 0, width: 54, height: 54, child: Container(decoration: BoxDecoration(shape: BoxShape.circle, color: Color(0xFFD8001B)))),
Positioned(left: 12, top: 12, width: 30, height: 30, child: Icon(IconData(0xED6F, fontFamily: 'lightIconFont'), size: 30, color: Color(0xFFFFFFFF)))
]))
])),
  Positioned(left: 53.9, top: 467.3, width: 260, height: 40, child: Container(decoration: BoxDecoration(color: Color(0xFF000000), borderRadius: BorderRadius.circular(10)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('原型：查看已绑定状态', textAlign: TextAlign.center, style: TextStyle(fontSize: 16, color: Color(0xFFFFFFFF), height: 1.25), overflow: TextOverflow.visible))),
]));
  }
}