// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
// ignore_for_file: use_key_in_widget_constructors
// ignore_for_file: file_names, camel_case_types
import 'package:flutter/material.dart';

/// APP登录方式选择 (租户-APP端/会员端登录(APP))
class cnulI2qsvBQPage extends StatelessWidget {
  const cnulI2qsvBQPage({super.key});

  @override
  Widget build(BuildContext context) {
return SizedBox(width: 971, height: 870, child: Stack(children: [
  Positioned(left: -532, top: 0, width: 375, height: 812, child: ClipRRect(borderRadius: BorderRadius.circular(0), child: Image.asset('assets/images/13f36a00-c5fd-11ec-a2a2-933d8a64c563.png', fit: BoxFit.contain, width: 375, height: 812))),
  Positioned(left: -945, top: 0, width: 375, height: 620, child: Stack(children: [
Positioned.fill(child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.only(topLeft: Radius.circular(16), topRight: Radius.circular(16), bottomRight: Radius.circular(0), bottomLeft: Radius.circular(0))))),
Positioned(left: 32.3, top: 395, width: 311, height: 48, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(2), border: Border.all(color: Color(0xFFEFF0F1), width: 1)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('通过AppleID继续', textAlign: TextAlign.center, style: TextStyle(fontSize: 14, color: Color(0xFF333333), fontWeight: FontWeight.w700, height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 32.3, top: 281, width: 311, height: 48, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(2), border: Border.all(color: Color(0xFFEFF0F1), width: 1)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('通过Gooogle继续', textAlign: TextAlign.center, style: TextStyle(fontSize: 14, color: Color(0xFF333333), fontWeight: FontWeight.w700, height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 32.3, top: 225, width: 311, height: 48, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(2), border: Border.all(color: Color(0xFFEFF0F1), width: 1)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('通过Facebook继续', textAlign: TextAlign.center, style: TextStyle(fontSize: 14, color: Color(0xFF333333), fontWeight: FontWeight.w700, height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 48, top: 407, width: 24, height: 24, child: Stack(children: [
Positioned(left: 0, top: 0, width: 24, height: 24, child: Container(decoration: BoxDecoration(shape: BoxShape.circle, color: Color(0xFF555555)))),
Positioned(left: 5.8, top: 5.8, width: 12, height: 12, child: Icon(IconData(0xED71, fontFamily: 'lightIconFont'), size: 12, color: Color(0xFFFFFFFF)))
])),
Positioned(left: 32.3, top: 169, width: 311, height: 48, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(2), border: Border.all(color: Color(0xFFEFF0F1), width: 1)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('使用手机/电子邮件/用户名', textAlign: TextAlign.center, style: TextStyle(fontSize: 14, color: Color(0xFF333333), fontWeight: FontWeight.w700, height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 48.3, top: 237, width: 24, height: 24, child: Stack(children: [
Positioned(left: 0, top: 0, width: 24, height: 24, child: Container(decoration: BoxDecoration(shape: BoxShape.circle, color: Color(0xFF555555)))),
Positioned(left: 1.8, top: 3.8, width: 20, height: 20, child: Icon(IconData(0xED60, fontFamily: 'lightIconFont'), size: 20, color: Color(0xFFFFFFFF)))
])),
Positioned(left: 32.3, top: 80, width: 311, height: 34, child: SizedBox.shrink()),
Positioned(left: 32.3, top: 122, width: 311, height: 18, child: SizedBox.shrink()),
Positioned(left: 50, top: 183, width: 20, height: 20, child: Icon(IconData(0xEB83, fontFamily: 'lightIconFont'), size: 20, color: Color(0xFF555555))),
Positioned(left: 32.3, top: 337, width: 311, height: 48, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(2), border: Border.all(color: Color(0xFFEFF0F1), width: 1)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('通过Twitter继续', textAlign: TextAlign.center, style: TextStyle(fontSize: 14, color: Color(0xFF333333), fontWeight: FontWeight.w700, height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 32.3, top: 451, width: 311, height: 48, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(2), border: Border.all(color: Color(0xFFEFF0F1), width: 1)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('通过Instagram继续', textAlign: TextAlign.center, style: TextStyle(fontSize: 14, color: Color(0xFF333333), fontWeight: FontWeight.w700, height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 50, top: 351, width: 20, height: 20, child: Icon(IconData(0xED88, fontFamily: 'lightIconFont'), size: 20, color: Color(0xFF555555))),
Positioned(left: 50, top: 295, width: 20, height: 20, child: Icon(IconData(0xED61, fontFamily: 'lightIconFont'), size: 20, color: Color(0xFF555555))),
Positioned(left: 50, top: 465, width: 20, height: 20, child: Icon(IconData(0xED7E, fontFamily: 'lightIconFont'), size: 20, color: Color(0xFF555555))),
Positioned(left: 22, top: 21, width: 20, height: 20, child: Icon(IconData(0xEA5B, fontFamily: 'boldIconFont'), size: 20, color: Color(0xFF333333)))
])),
  Positioned(left: 64, top: 65, width: 375, height: 667, child: Stack(children: [
Positioned.fill(child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF)))),
Positioned(left: 0, top: 0, width: 375, height: 20, child: Stack(children: [
Positioned(left: 0, top: 0, width: 375, height: 20, child: Stack(children: [
Positioned(left: 0, top: 0, width: 375, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), alignment: Alignment.centerLeft, padding: EdgeInsets.only(left: 6, top: 0, right: 8, bottom: 0))),
Positioned(left: 349, top: 2, width: 16, height: 16, child: Icon(IconData(0xEB08, fontFamily: 'lightIconFont'), size: 16, color: Color(0xFF333333))),
Positioned(left: 45, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E8, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333))),
Positioned(left: 305, top: 6, width: 8, height: 8, child: Icon(IconData(0xEB10, fontFamily: 'lightIconFont'), size: 8, color: Color(0xFF333333))),
Positioned(left: 73, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E7, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333))),
Positioned(left: 6, top: 7, width: 30, height: 5, child: Stack(children: [
Positioned(left: 0, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 6, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 13, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 19, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 25, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1F, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF7F7F7F)))
])),
Positioned(left: 318, top: 5, width: 26, height: 10, child: SizedBox.shrink()),
Positioned(left: 59, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E8, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333)))
]))
])),
Positioned(left: 0, top: 0, width: 375, height: 48, child: Container(decoration: BoxDecoration(color: Color(0x997E7F80), borderRadius: BorderRadius.circular(0))))
])),
  Positioned(left: 64, top: 85, width: 375, height: 647, child: Stack(children: [
Positioned.fill(child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.only(topLeft: Radius.circular(4), topRight: Radius.circular(4), bottomRight: Radius.circular(0), bottomLeft: Radius.circular(0))))),
Positioned(left: 38.5, top: 472, width: 300, height: 40, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(2), border: Border.all(color: Color(0xFFEFF0F1), width: 1)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('通过AppleID继续', textAlign: TextAlign.center, style: TextStyle(fontSize: 12, color: Color(0xFF000000), fontWeight: FontWeight.w700, height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 38.5, top: 328, width: 300, height: 40, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(2), border: Border.all(color: Color(0xFFEFF0F1), width: 1)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('通过Gooogle继续', textAlign: TextAlign.center, style: TextStyle(fontSize: 12, color: Color(0xFF000000), fontWeight: FontWeight.w700, height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 38.5, top: 280, width: 300, height: 40, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(2), border: Border.all(color: Color(0xFFEFF0F1), width: 1)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('通过Facebook继续', textAlign: TextAlign.center, style: TextStyle(fontSize: 12, color: Color(0xFF000000), fontWeight: FontWeight.w700, height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 54.2, top: 484, width: 24, height: 24, child: Container(decoration: BoxDecoration(shape: BoxShape.circle, color: Color(0xFF000000)))),
Positioned(left: 60.0, top: 489.8, width: 12, height: 12, child: Icon(IconData(0xED71, fontFamily: 'lightIconFont'), size: 12, color: Color(0xFFFFFFFF))),
Positioned(left: 38.5, top: 136, width: 300, height: 40, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(2), border: Border.all(color: Color(0xFFEFF0F1), width: 1)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('使用密码(手机/电子邮件/用户名)', textAlign: TextAlign.center, style: TextStyle(fontSize: 12, color: Color(0xFF000000), fontWeight: FontWeight.w700, height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 54.5, top: 292, width: 24, height: 24, child: Container(decoration: BoxDecoration(shape: BoxShape.circle, color: Color(0xFF116CDB)))),
Positioned(left: 58.3, top: 295.8, width: 16, height: 16, child: Icon(IconData(0xED60, fontFamily: 'lightIconFont'), size: 16, color: Color(0xFFFFFFFF))),
Positioned(left: 32.5, top: 60, width: 311, height: 34, child: SizedBox.shrink()),
Positioned(left: 32.5, top: 102, width: 311, height: 18, child: SizedBox.shrink()),
Positioned(left: 38.5, top: 376, width: 300, height: 40, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(2), border: Border.all(color: Color(0xFFEFF0F1), width: 1)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('通过Twitter继续', textAlign: TextAlign.center, style: TextStyle(fontSize: 12, color: Color(0xFF000000), fontWeight: FontWeight.w700, height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 38.5, top: 424, width: 300, height: 40, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(2), border: Border.all(color: Color(0xFFEFF0F1), width: 1)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('通过Instagram继续', textAlign: TextAlign.center, style: TextStyle(fontSize: 12, color: Color(0xFF000000), fontWeight: FontWeight.w700, height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 56.2, top: 390, width: 20, height: 20, child: Icon(IconData(0xED88, fontFamily: 'lightIconFont'), size: 20, color: Color(0xFF116CDB))),
Positioned(left: 56.2, top: 438, width: 20, height: 20, child: Icon(IconData(0xED7E, fontFamily: 'lightIconFont'), size: 20, color: Color(0xFFD8001B))),
Positioned(left: 338, top: 18, width: 16, height: 16, child: Icon(IconData(0xEA81, fontFamily: 'lightIconFont'), size: 16, color: Color(0xFF333333))),
Positioned(left: 38.5, top: 184, width: 300, height: 40, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(2), border: Border.all(color: Color(0xFFEFF0F1), width: 1)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('通过手机短信继续', textAlign: TextAlign.center, style: TextStyle(fontSize: 12, color: Color(0xFF000000), fontWeight: FontWeight.w700, height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 38.5, top: 232, width: 300, height: 40, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(2), border: Border.all(color: Color(0xFFEFF0F1), width: 1)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('通过邮箱继续', textAlign: TextAlign.center, style: TextStyle(fontSize: 12, color: Color(0xFF000000), fontWeight: FontWeight.w700, height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 583, width: 375, height: 64, child: Container(decoration: BoxDecoration(color: Color(0xFFF7F8F9), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('还没有账号？ ', textAlign: TextAlign.center, style: TextStyle(fontSize: 14, color: Color(0xFF333333), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 54.2, top: 192, width: 24, height: 24, child: Container(decoration: BoxDecoration(shape: BoxShape.circle, color: Color(0xFFD05177)))),
Positioned(left: 60.2, top: 198, width: 12, height: 12, child: Icon(IconData(0xEAFB, fontFamily: 'boldIconFont'), size: 12, color: Color(0xFFFFFFFF))),
Positioned(left: 54.2, top: 144, width: 24, height: 24, child: Container(decoration: BoxDecoration(shape: BoxShape.circle, color: Color(0xFF3B81CB)))),
Positioned(left: 60.2, top: 150, width: 12, height: 12, child: Icon(IconData(0xEB4D, fontFamily: 'boldIconFont'), size: 12, color: Color(0xFFFFFFFF))),
Positioned(left: 54.2, top: 240, width: 24, height: 24, child: Container(decoration: BoxDecoration(shape: BoxShape.circle, color: Color(0xFFC53D31)))),
Positioned(left: 60.2, top: 246, width: 12, height: 12, child: Icon(IconData(0xE87E, fontFamily: 'boldIconFont'), size: 12, color: Color(0xFFFFFFFF))),
Positioned(left: 54.2, top: 336, width: 24, height: 24, child: Icon(IconData(0xE882, fontFamily: 'boldIconFont'), size: 24, color: Color(0xFFE1A904))),
Positioned(left: 39, top: 546, width: 300, height: 32, child: SizedBox.shrink())
])),
  Positioned(left: 497, top: 65, width: 375, height: 667, child: Stack(children: [
Positioned.fill(child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF)))),
Positioned(left: 0, top: 0, width: 375, height: 20, child: Stack(children: [
Positioned(left: 0, top: 0, width: 375, height: 20, child: Stack(children: [
Positioned(left: 0, top: 0, width: 375, height: 20, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(0), boxShadow: [BoxShadow(color: Color(0x26000000), blurRadius: 0, offset: Offset(0, 0))]), alignment: Alignment.centerLeft, padding: EdgeInsets.only(left: 6, top: 0, right: 8, bottom: 0))),
Positioned(left: 349, top: 2, width: 16, height: 16, child: Icon(IconData(0xEB08, fontFamily: 'lightIconFont'), size: 16, color: Color(0xFF333333))),
Positioned(left: 45, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E8, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333))),
Positioned(left: 305, top: 6, width: 8, height: 8, child: Icon(IconData(0xEB10, fontFamily: 'lightIconFont'), size: 8, color: Color(0xFF333333))),
Positioned(left: 73, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E7, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333))),
Positioned(left: 6, top: 7, width: 30, height: 5, child: Stack(children: [
Positioned(left: 0, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 6, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 13, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 19, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 25, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1F, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF7F7F7F)))
])),
Positioned(left: 318, top: 5, width: 26, height: 10, child: SizedBox.shrink()),
Positioned(left: 59, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E8, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333)))
]))
])),
Positioned(left: 0, top: 0, width: 375, height: 48, child: Container(decoration: BoxDecoration(color: Color(0x997E7F80), borderRadius: BorderRadius.circular(0), boxShadow: [BoxShadow(color: Color(0x26000000), blurRadius: 0, offset: Offset(0, 0))])))
])),
  Positioned(left: 497, top: 85, width: 375, height: 647, child: Stack(children: [
Positioned.fill(child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.only(topLeft: Radius.circular(4), topRight: Radius.circular(4), bottomRight: Radius.circular(0), bottomLeft: Radius.circular(0))))),
Positioned(left: 39, top: 480, width: 300, height: 40, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(2), border: Border.all(color: Color(0xFFEFF0F1), width: 1), boxShadow: [BoxShadow(color: Color(0x26000000), blurRadius: 0, offset: Offset(0, 0))]), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('Continue with AppleID', textAlign: TextAlign.center, style: TextStyle(fontSize: 12, color: Color(0xFF000000), height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 39, top: 336, width: 300, height: 40, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(2), border: Border.all(color: Color(0xFFEFF0F1), width: 1), boxShadow: [BoxShadow(color: Color(0x26000000), blurRadius: 0, offset: Offset(0, 0))]), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('Continue with Gooogle', textAlign: TextAlign.center, style: TextStyle(fontSize: 12, color: Color(0xFF000000), height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 39, top: 288, width: 300, height: 40, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(2), border: Border.all(color: Color(0xFFEFF0F1), width: 1), boxShadow: [BoxShadow(color: Color(0x26000000), blurRadius: 0, offset: Offset(0, 0))]), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('Contine with Facebook', textAlign: TextAlign.center, style: TextStyle(fontSize: 12, color: Color(0xFF000000), height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 54, top: 492, width: 24, height: 24, child: Container(decoration: BoxDecoration(shape: BoxShape.circle, color: Color(0xFF000000)))),
Positioned(left: 60, top: 498, width: 12, height: 12, child: Icon(IconData(0xED71, fontFamily: 'lightIconFont'), size: 12, color: Color(0xFFFFFFFF))),
Positioned(left: 39, top: 144, width: 300, height: 40, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(2), border: Border.all(color: Color(0xFFEFF0F1), width: 1), boxShadow: [BoxShadow(color: Color(0x26000000), blurRadius: 0, offset: Offset(0, 0))]), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('Use username', textAlign: TextAlign.center, style: TextStyle(fontSize: 12, color: Color(0xFF000000), height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 55, top: 300, width: 24, height: 24, child: Container(decoration: BoxDecoration(shape: BoxShape.circle, color: Color(0xFF116CDB)))),
Positioned(left: 58, top: 304, width: 16, height: 16, child: Icon(IconData(0xED60, fontFamily: 'lightIconFont'), size: 16, color: Color(0xFFFFFFFF))),
Positioned(left: 33, top: 60, width: 311, height: 34, child: SizedBox.shrink()),
Positioned(left: 33, top: 102, width: 311, height: 18, child: SizedBox.shrink()),
Positioned(left: 39, top: 384, width: 300, height: 40, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(2), border: Border.all(color: Color(0xFFEFF0F1), width: 1), boxShadow: [BoxShadow(color: Color(0x26000000), blurRadius: 0, offset: Offset(0, 0))]), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('Continue with Twitter', textAlign: TextAlign.center, style: TextStyle(fontSize: 12, color: Color(0xFF000000), height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 39, top: 432, width: 300, height: 40, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(2), border: Border.all(color: Color(0xFFEFF0F1), width: 1), boxShadow: [BoxShadow(color: Color(0x26000000), blurRadius: 0, offset: Offset(0, 0))]), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('Continue with Instagram', textAlign: TextAlign.center, style: TextStyle(fontSize: 12, color: Color(0xFF000000), height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 56, top: 398, width: 20, height: 20, child: Icon(IconData(0xED88, fontFamily: 'lightIconFont'), size: 20, color: Color(0xFF116CDB))),
Positioned(left: 56, top: 446, width: 20, height: 20, child: Icon(IconData(0xED7E, fontFamily: 'lightIconFont'), size: 20, color: Color(0xFFD8001B))),
Positioned(left: 338, top: 18, width: 16, height: 16, child: Icon(IconData(0xEA81, fontFamily: 'lightIconFont'), size: 16, color: Color(0xFF333333))),
Positioned(left: 39, top: 192, width: 300, height: 40, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(2), border: Border.all(color: Color(0xFFEFF0F1), width: 1), boxShadow: [BoxShadow(color: Color(0x26000000), blurRadius: 0, offset: Offset(0, 0))]), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('Use phone', textAlign: TextAlign.center, style: TextStyle(fontSize: 12, color: Color(0xFF000000), height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 39, top: 240, width: 300, height: 40, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(2), border: Border.all(color: Color(0xFFEFF0F1), width: 1), boxShadow: [BoxShadow(color: Color(0x26000000), blurRadius: 0, offset: Offset(0, 0))]), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('Use email', textAlign: TextAlign.center, style: TextStyle(fontSize: 12, color: Color(0xFF000000), height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 583, width: 375, height: 64, child: Container(decoration: BoxDecoration(color: Color(0xFFF7F8F9), borderRadius: BorderRadius.circular(0), boxShadow: [BoxShadow(color: Color(0x26000000), blurRadius: 0, offset: Offset(0, 0))]), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('Don\'t have an account？ ', textAlign: TextAlign.left, overflow: TextOverflow.visible))),
Positioned(left: 54, top: 200, width: 24, height: 24, child: Container(decoration: BoxDecoration(shape: BoxShape.circle, color: Color(0xFFD05177)))),
Positioned(left: 60, top: 206, width: 12, height: 12, child: Icon(IconData(0xEAFB, fontFamily: 'boldIconFont'), size: 12, color: Color(0xFFFFFFFF))),
Positioned(left: 54, top: 152, width: 24, height: 24, child: Container(decoration: BoxDecoration(shape: BoxShape.circle, color: Color(0xFF3B81CB)))),
Positioned(left: 54, top: 248, width: 24, height: 24, child: Container(decoration: BoxDecoration(shape: BoxShape.circle, color: Color(0xFFC53D31)))),
Positioned(left: 60, top: 254, width: 12, height: 12, child: Icon(IconData(0xE87E, fontFamily: 'boldIconFont'), size: 12, color: Color(0xFFFFFFFF))),
Positioned(left: 54, top: 344, width: 24, height: 24, child: Icon(IconData(0xE882, fontFamily: 'boldIconFont'), size: 24, color: Color(0xFFE1A904))),
Positioned(left: 60, top: 158, width: 12, height: 12, child: Icon(IconData(0xEB4D, fontFamily: 'boldIconFont'), size: 12, color: Color(0xFFFFFFFF))),
Positioned(left: 39.0, top: 534.6, width: 300, height: 48, child: SizedBox.shrink())
])),
]));
  }
}