// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
// ignore_for_file: use_key_in_widget_constructors
// ignore_for_file: file_names, camel_case_types
import 'package:flutter/material.dart';

/// 检测到手机号未注册 (租户-APP端/会员端登录(APP)/手机验证码登录)
class d4kpcMYob7uPage extends StatelessWidget {
  const d4kpcMYob7uPage({super.key});

  @override
  Widget build(BuildContext context) {
return SizedBox(width: 375, height: 667, child: Stack(children: [
  Positioned(left: -366, top: 0, width: 303, height: 364, child: ColoredBox(color: Color(0xFFFFDF25))),
  Positioned(left: 0, top: 0, width: 375, height: 20, child: Stack(children: [
Positioned(left: 0, top: 0, width: 375, height: 20, child: Stack(children: [
Positioned(left: 0, top: 0, width: 375, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), alignment: Alignment.centerLeft, padding: EdgeInsets.only(left: 6, top: 0, right: 8, bottom: 0))),
Positioned(left: 349, top: 2, width: 16, height: 16, child: Icon(IconData(0xEB08, fontFamily: 'lightIconFont'), size: 16, color: Color(0xFF333333))),
Positioned(left: 45, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E8, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333))),
Positioned(left: 305, top: 6, width: 8, height: 8, child: Icon(IconData(0xEB10, fontFamily: 'lightIconFont'), size: 8, color: Color(0xFF333333))),
Positioned(left: 73, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E7, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333))),
Positioned(left: 6, top: 7, width: 30, height: 5, child: Stack(children: [
Positioned(left: 0, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 6, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 13, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 19, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 25, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1F, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF7F7F7F)))
])),
Positioned(left: 318, top: 5, width: 26, height: 10, child: SizedBox.shrink()),
Positioned(left: 59, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E8, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333)))
]))
])),
  Positioned(left: 96, top: 120, width: 255, height: 48, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(4), border: Border(bottom: BorderSide(color: Color(0xFFD7D7D7), width: 1))), alignment: Alignment.centerLeft, padding: EdgeInsets.only(left: 8, top: 0, right: 8, bottom: 0), child: Text('15020579521', style: TextStyle(fontSize: 12, color: Color(0xFF000000), fontWeight: FontWeight.w700), overflow: TextOverflow.ellipsis))),
  Positioned(left: 24, top: 280, width: 327, height: 40, child: Stack(children: [
Positioned.fill(child: Container(decoration: BoxDecoration(color: Color(0xFF000000), borderRadius: BorderRadius.circular(24)))),
Positioned(left: 143, top: 11, width: 42, height: 17, child: Text('下一步', textAlign: TextAlign.left, overflow: TextOverflow.visible))
])),
  Positioned(left: 24, top: 120, width: 72, height: 48, child: Stack(children: [
Positioned(left: 0, top: 0, width: 72, height: 48, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(0), border: Border(bottom: BorderSide(color: Color(0xFFD7D7D7), width: 1))), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('CN  +86', textAlign: TextAlign.left, style: TextStyle(fontSize: 12, color: Color(0xFF000000), height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 56, top: 20, width: 8, height: 8, child: Icon(IconData(0xE783, fontFamily: 'boldIconFont'), size: 8, color: Color(0xFF000000)))
])),
  Positioned(left: 333, top: 144, width: 12, height: 12, child: Icon(IconData(0xEA7F, fontFamily: 'boldIconFont'), size: 12, color: Color(0xFFD7D7D7))),
  Positioned(left: 24, top: 344, width: 310, height: 30, child: Stack(children: [
Positioned(left: 18, top: 0, width: 292, height: 30, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('已阅读并同意 ', textAlign: TextAlign.left, style: TextStyle(fontSize: 10, color: Color(0xFF333333), height: 1.20), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 0, width: 23, height: 17, child: Stack(children: [
Positioned.fill(child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(0), border: Border.all(color: Color(0xFF000000), width: 1), boxShadow: [BoxShadow(color: Color(0x26000000), blurRadius: 0, offset: Offset(0, 0))]))),
Positioned(left: 0, top: 2, width: 13, height: 13, child: Stack(children: [
Positioned.fill(child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(100), border: Border.all(color: Color(0xFF777777), width: 1), boxShadow: [BoxShadow(color: Color(0x26000000), blurRadius: 0, offset: Offset(0, 0))]))),
Positioned(left: 3, top: 3, width: 7, height: 7, child: Container(decoration: BoxDecoration(color: Color(0xFF777777), borderRadius: BorderRadius.circular(100), border: Border.all(color: Color(0xFF000000), width: 1), boxShadow: [BoxShadow(color: Color(0x26000000), blurRadius: 0, offset: Offset(0, 0))])))
])),
Positioned(left: 23, top: 0, height: 17, child: SizedBox.shrink())
]))
])),
  Positioned(left: 291, top: 176, width: 60, height: 18, child: SizedBox.shrink()),
  Positioned(left: 0, top: 20, width: 375, height: 44, child: Stack(children: [
Positioned(left: 44, top: 0, width: 255, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('登录', textAlign: TextAlign.center, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 0, width: 16, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 16, top: 0, width: 28, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 359, top: 0, width: 16, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 299, top: 0, width: 60, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 14, width: 16, height: 16, child: Icon(IconData(0xE998, fontFamily: 'boldIconFont'), size: 16, color: Color(0xFF000000)))
])),
  Positioned(left: 0, top: 467, width: 375, height: 200, child: Container(width: 375, height: 200, decoration: BoxDecoration(color: Color(0xFFD9D9D9)))),
  Positioned(left: 0, top: 0, width: 375, height: 667, child: Container(decoration: BoxDecoration(color: Color(0x997E7F80), borderRadius: BorderRadius.circular(0)))),
  Positioned(left: 38, top: 213, width: 300, height: 173, child: Stack(children: [
Positioned.fill(child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(4), boxShadow: [BoxShadow(color: Color(0x26000000), blurRadius: 6, offset: Offset(0, 3))]))),
Positioned(left: 18, top: 130, width: 110, height: 30, child: Stack(children: [
Positioned.fill(child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(4), border: Border.all(color: Color(0xFFF2F2F2), width: 1)))),
Positioned(left: 41, top: 6.5, width: 28, height: 17, child: Text('取消', textAlign: TextAlign.left, overflow: TextOverflow.visible))
])),
Positioned(left: 168, top: 130, width: 110, height: 30, child: Stack(children: [
Positioned.fill(child: Container(decoration: BoxDecoration(color: Color(0xFF000000), borderRadius: BorderRadius.circular(4)))),
Positioned(left: 27, top: 6.5, width: 56, height: 17, child: Text('继续注册', textAlign: TextAlign.left, overflow: TextOverflow.visible))
])),
Positioned(left: 0, top: 15, width: 300, height: 74, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 32, right: 32, top: 0, bottom: 0), child: Text('手机号未注册+86 15020579521', textAlign: TextAlign.left, style: TextStyle(fontWeight: FontWeight.w700), overflow: TextOverflow.visible)))
])),
]));
  }
}