// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
// ignore_for_file: use_key_in_widget_constructors
// ignore_for_file: file_names, camel_case_types
import 'package:flutter/material.dart';

/// (APP)用户个人中心 (1) (租户-APP端/APP/H5-个人中心)
class E1Oa0Pvm6BOPage extends StatelessWidget {
  const E1Oa0Pvm6BOPage({super.key});

  @override
  Widget build(BuildContext context) {
return SizedBox(width: 375, height: 667, child: Stack(children: [
  Positioned(left: -515, top: 618.3, width: 375, height: 49, child: Stack(children: [
Positioned.fill(child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF)))),
Positioned(left: 0, top: 0, width: 94, height: 49, child: Stack(children: [
Positioned(left: 0, top: 0, width: 94, height: 29, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0), border: Border(top: BorderSide(color: Color(0xFFF6F7F8), width: 1))))),
Positioned(left: 39, top: 13, width: 16, height: 16, child: Icon(IconData(0xEBA7, fontFamily: 'lightIconFont'), size: 16, color: Color(0xFFBFC5CA))),
Positioned(left: 0, top: 29, width: 94, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 2, bottom: 4), child: Text('家', textAlign: TextAlign.center, style: TextStyle(fontSize: 12, color: Color(0xFFBFC5CA), height: 1.67), overflow: TextOverflow.visible)))
])),
Positioned(left: 94, top: 0, width: 94, height: 49, child: Stack(children: [
Positioned(left: 0, top: 0, width: 94, height: 29, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0), border: Border(top: BorderSide(color: Color(0xFFF6F7F8), width: 1))))),
Transform.rotate(angle: 1.5708, child: Positioned(left: 39, top: 13, width: 16, height: 16, child: Icon(IconData(0xE977, fontFamily: 'lightIconFont'), size: 16, color: Color(0xFFBFC5CA)))),
Positioned(left: 0, top: 29, width: 94, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 2, bottom: 4), child: Text('房间', textAlign: TextAlign.center, style: TextStyle(fontSize: 12, color: Color(0xFFBFC5CA), height: 1.67), overflow: TextOverflow.visible)))
])),
Positioned(left: 188, top: 0, width: 94, height: 49, child: Stack(children: [
Positioned(left: 0, top: 0, width: 94, height: 29, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0), border: Border(top: BorderSide(color: Color(0xFFF6F7F8), width: 1))))),
Positioned(left: 39, top: 13, width: 16, height: 16, child: Icon(IconData(0xEB47, fontFamily: 'lightIconFont'), size: 16, color: Color(0xFFBFC5CA))),
Positioned(left: 0, top: 29, width: 94, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 2, bottom: 4), child: Text('场景', textAlign: TextAlign.center, style: TextStyle(fontSize: 12, color: Color(0xFFBFC5CA), height: 1.67), overflow: TextOverflow.visible)))
])),
Positioned(left: 282, top: 0, width: 93, height: 49, child: Stack(children: [
Positioned(left: 0, top: 0, width: 93, height: 29, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0), border: Border(top: BorderSide(color: Color(0xFFF6F7F8), width: 1))))),
Positioned(left: 38, top: 13, width: 16, height: 16, child: Icon(IconData(0xEBA9, fontFamily: 'lightIconFont'), size: 16, color: Color(0xFF3EB5AE))),
Positioned(left: 0, top: 29, width: 93, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 2, bottom: 4), child: Text('我的', textAlign: TextAlign.center, style: TextStyle(fontSize: 12, color: Color(0xFF3EB5AE), height: 1.67), overflow: TextOverflow.visible)))
]))
])),
  Positioned(left: 0, top: 0, width: 375, height: 20, child: Stack(children: [
Positioned(left: 0, top: 0, width: 375, height: 20, child: Stack(children: [
Positioned(left: 0, top: 0, width: 375, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), alignment: Alignment.centerLeft, padding: EdgeInsets.only(left: 6, top: 0, right: 8, bottom: 0))),
Positioned(left: 349, top: 2, width: 16, height: 16, child: Icon(IconData(0xEB08, fontFamily: 'lightIconFont'), size: 16, color: Color(0xFF333333))),
Positioned(left: 45, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E8, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333))),
Positioned(left: 305, top: 6, width: 8, height: 8, child: Icon(IconData(0xEB10, fontFamily: 'lightIconFont'), size: 8, color: Color(0xFF333333))),
Positioned(left: 73, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E7, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333))),
Positioned(left: 6, top: 7, width: 30, height: 5, child: Stack(children: [
Positioned(left: 0, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 6, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 13, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 19, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 25, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1F, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF7F7F7F)))
])),
Positioned(left: 318, top: 5, width: 26, height: 10, child: SizedBox.shrink()),
Positioned(left: 59, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E8, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333)))
]))
])),
  Positioned(left: 24, top: 60, width: 327.1, height: 64, child: Stack(children: [
Positioned(left: 0, top: 0, width: 64, height: 64, child: ClipRRect(borderRadius: BorderRadius.circular(100), child: Image.asset('assets/images/41b4fff0-a4e1-11eb-b082-a72ce0a75548.png', fit: BoxFit.contain, width: 64, height: 64))),
Positioned(left: 77, top: 40, width: 250, height: 24, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('N个智能设备', textAlign: TextAlign.left, style: TextStyle(fontSize: 12, color: Color(0xFF7F8B96), height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 77, top: 0, width: 250, height: 40, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('avey', textAlign: TextAlign.left, style: TextStyle(fontSize: 28, height: 0.71), overflow: TextOverflow.visible)))
])),
]));
  }
}