// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
// ignore_for_file: use_key_in_widget_constructors
// ignore_for_file: file_names, camel_case_types
import 'package:flutter/material.dart';

/// 账号日志 (租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全)
class F4wEnb2CNZsPage extends StatelessWidget {
  const F4wEnb2CNZsPage({super.key});

  @override
  Widget build(BuildContext context) {
return SizedBox(width: 375, height: 667, child: Stack(children: [
  Positioned(left: 0, top: 0, width: 375, height: 20, child: Stack(children: [
Positioned(left: 0, top: 0, width: 375, height: 20, child: Stack(children: [
Positioned(left: 0, top: 0, width: 375, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), alignment: Alignment.centerLeft, padding: EdgeInsets.only(left: 6, top: 0, right: 8, bottom: 0))),
Positioned(left: 349, top: 2, width: 16, height: 16, child: Icon(IconData(0xEB08, fontFamily: 'lightIconFont'), size: 16, color: Color(0xFF333333))),
Positioned(left: 45, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E8, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333))),
Positioned(left: 305, top: 6, width: 8, height: 8, child: Icon(IconData(0xEB10, fontFamily: 'lightIconFont'), size: 8, color: Color(0xFF333333))),
Positioned(left: 73, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E7, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333))),
Positioned(left: 6, top: 7, width: 30, height: 5, child: Stack(children: [
Positioned(left: 0, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 6, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 13, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 19, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 25, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1F, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF7F7F7F)))
])),
Positioned(left: 318, top: 5, width: 26, height: 10, child: SizedBox.shrink()),
Positioned(left: 59, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E8, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333)))
]))
])),
  Positioned(left: 0, top: 20, width: 375, height: 44, child: Stack(children: [
Positioned(left: 44, top: 0, width: 287, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('账号日志', textAlign: TextAlign.center, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 0, width: 16, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 16, top: 0, width: 28, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 359, top: 0, width: 16, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 331, top: 0, width: 28, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 14, width: 16, height: 16, child: Icon(IconData(0xE998, fontFamily: 'boldIconFont'), size: 16, color: Color(0xFF000000))),
Positioned(left: 0, top: 0, width: 44, height: 44, child: SizedBox.shrink())
])),
  Positioned(left: 0, top: 88, width: 375, height: 50, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 20, right: 20, top: 0, bottom: 0), child: Text('2020-11-17', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF777777), height: 1.25), overflow: TextOverflow.visible))),
  Positioned(left: 0, top: 138, width: 414, height: 50, child: Stack(children: [
Positioned(left: 348, top: 20, width: 30, height: 30, child: Stack(children: [
Positioned(left: 0, top: 0, width: 27, height: 30, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 0, top: 9, width: 12, height: 12, child: Icon(IconData(0xE9BE, fontFamily: 'lightIconFont'), size: 12, color: Color(0xFF7F7F7F)))
])),
Positioned(left: 0, top: 20, width: 60, height: 30, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 60, top: 20, width: 224, height: 30, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('广东省  深圳市', textAlign: TextAlign.left, style: TextStyle(fontSize: 12, color: Color(0xFF7F7F7F), height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 245, top: 20, width: 100, height: 30, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 6, top: 0, bottom: 0), child: Text('16:09', textAlign: TextAlign.right, style: TextStyle(fontSize: 12, color: Color(0xFF7F7F7F), height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 60, top: 0, width: 315, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('nova 5 Pro  登陆', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFF000000), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 14, top: 5, width: 30, height: 30, child: Stack(children: [
Positioned(left: 0, top: 0, width: 27, height: 27, child: Container(decoration: BoxDecoration(shape: BoxShape.circle, color: Color(0xFFD9DADB)))),
Positioned(left: 6, top: 7, width: 15, height: 15, child: Icon(IconData(0xEB2B, fontFamily: 'lightIconFont'), size: 15, color: Color(0xFFFFFFFF)))
])),
Positioned(left: 60, top: 0, width: 315, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('nova 5 Pro  登录', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFF000000), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 14, top: 5, width: 30, height: 30, child: Stack(children: [
Positioned(left: 0, top: 0, width: 27, height: 27, child: Container(decoration: BoxDecoration(shape: BoxShape.circle, color: Color(0xFFD9DADB)))),
Positioned(left: 6, top: 7, width: 15, height: 15, child: Icon(IconData(0xEB2B, fontFamily: 'lightIconFont'), size: 15, color: Color(0xFFFFFFFF)))
]))
])),
  Positioned(left: 0, top: 188, width: 375, height: 50, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 20, right: 20, top: 0, bottom: 0), child: Text('2020-11-10', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF777777), height: 1.25), overflow: TextOverflow.visible))),
  Positioned(left: 0, top: 238, width: 414, height: 50, child: Stack(children: [
Positioned(left: 348, top: 20, width: 30, height: 30, child: Stack(children: [
Positioned(left: 0, top: 0, width: 27, height: 30, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 0, top: 9, width: 12, height: 12, child: Icon(IconData(0xE9BE, fontFamily: 'lightIconFont'), size: 12, color: Color(0xFF7F7F7F)))
])),
Positioned(left: 0, top: 20, width: 60, height: 30, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 60, top: 20, width: 224, height: 30, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('广东省  深圳市', textAlign: TextAlign.left, style: TextStyle(fontSize: 12, color: Color(0xFF7F7F7F), height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 245, top: 20, width: 100, height: 30, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 6, top: 0, bottom: 0), child: Text('16:09', textAlign: TextAlign.right, style: TextStyle(fontSize: 12, color: Color(0xFF7F7F7F), height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 60, top: 0, width: 315, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('nova 5 Pro  登录', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFF000000), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 14, top: 5, width: 30, height: 30, child: Stack(children: [
Positioned(left: 0, top: 0, width: 27, height: 27, child: Container(decoration: BoxDecoration(shape: BoxShape.circle, color: Color(0xFFD9DADB)))),
Positioned(left: 6, top: 7, width: 15, height: 15, child: Icon(IconData(0xEB2B, fontFamily: 'lightIconFont'), size: 15, color: Color(0xFFFFFFFF)))
]))
])),
  Positioned(left: 0, top: 297, width: 414, height: 50, child: Stack(children: [
Positioned(left: 348, top: 20, width: 30, height: 30, child: Stack(children: [
Positioned(left: 0, top: 0, width: 27, height: 30, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 0, top: 9, width: 12, height: 12, child: Icon(IconData(0xE9BE, fontFamily: 'lightIconFont'), size: 12, color: Color(0xFF7F7F7F)))
])),
Positioned(left: 0, top: 20, width: 60, height: 30, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 60, top: 20, width: 224, height: 30, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('广东省  深圳市', textAlign: TextAlign.left, style: TextStyle(fontSize: 12, color: Color(0xFF7F7F7F), height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 245, top: 20, width: 100, height: 30, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 6, top: 0, bottom: 0), child: Text('16:09', textAlign: TextAlign.right, style: TextStyle(fontSize: 12, color: Color(0xFF7F7F7F), height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 60, top: 0, width: 315, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('nova 5 Pro  登录', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFF000000), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 14, top: 1, width: 30, height: 30, child: Stack(children: [
Positioned(left: 6, top: 12, width: 15, height: 15, child: Icon(IconData(0xEB2B, fontFamily: 'lightIconFont'), size: 15, color: Color(0xFFFFFFFF))),
Positioned(left: 0, top: 0, width: 30, height: 30, child: Stack(children: [
Positioned(left: 0, top: 0, width: 27, height: 27, child: Container(decoration: BoxDecoration(shape: BoxShape.circle, color: Color(0xFFD9DADB)))),
Positioned(left: 6, top: 7, width: 15, height: 15, child: Icon(IconData(0xEB02, fontFamily: 'boldIconFont'), size: 15, color: Color(0xFFFFFFFF)))
]))
]))
])),
]));
  }
}