// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
// ignore_for_file: use_key_in_widget_constructors
// ignore_for_file: file_names, camel_case_types
import 'package:flutter/material.dart';

/// 输入邮件登录验证码 (租户-APP端/会员端登录(APP)/邮箱验证码登录)
class i944FAsAeupPage extends StatelessWidget {
  const i944FAsAeupPage({super.key});

  @override
  Widget build(BuildContext context) {
return SizedBox(width: 375, height: 667, child: Stack(children: [
  Positioned(left: 0, top: 0, width: 375, height: 20, child: Stack(children: [
Positioned(left: 0, top: 0, width: 375, height: 20, child: Stack(children: [
Positioned(left: 0, top: 0, width: 375, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), alignment: Alignment.centerLeft, padding: EdgeInsets.only(left: 6, top: 0, right: 8, bottom: 0))),
Positioned(left: 349, top: 2, width: 16, height: 16, child: Icon(IconData(0xEB08, fontFamily: 'lightIconFont'), size: 16, color: Color(0xFF333333))),
Positioned(left: 45, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E8, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333))),
Positioned(left: 305, top: 6, width: 8, height: 8, child: Icon(IconData(0xEB10, fontFamily: 'lightIconFont'), size: 8, color: Color(0xFF333333))),
Positioned(left: 73, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E7, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333))),
Positioned(left: 6, top: 7, width: 30, height: 5, child: Stack(children: [
Positioned(left: 0, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 6, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 13, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 19, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 25, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1F, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF7F7F7F)))
])),
Positioned(left: 318, top: 5, width: 26, height: 10, child: SizedBox.shrink()),
Positioned(left: 59, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E8, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333)))
]))
])),
  Positioned(left: 0, top: 20, width: 375, height: 44, child: Stack(children: [
Positioned(left: 44, top: 0, width: 287, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 0, top: 0, width: 16, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 16, top: 0, width: 28, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 359, top: 0, width: 16, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 331, top: 0, width: 28, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 14, width: 16, height: 16, child: Icon(IconData(0xE998, fontFamily: 'boldIconFont'), size: 16, color: Color(0xFF000000))),
Positioned(left: 0, top: 0, width: 44, height: 44, child: SizedBox.shrink())
])),
  Positioned(left: 24, top: 80, width: 132, height: 34, child: SizedBox.shrink()),
  Positioned(left: 24, top: 196, width: 44, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(2), border: Border.all(color: Color(0xFFD7D7D7), width: 1)), alignment: Alignment.centerLeft, padding: EdgeInsets.only(left: 8, top: 0, right: 8, bottom: 0))),
  Positioned(left: 81, top: 196, width: 44, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(2), border: Border.all(color: Color(0xFFD7D7D7), width: 1)), alignment: Alignment.centerLeft, padding: EdgeInsets.only(left: 8, top: 0, right: 8, bottom: 0))),
  Positioned(left: 138, top: 196, width: 44, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(2), border: Border.all(color: Color(0xFFD7D7D7), width: 1)), alignment: Alignment.centerLeft, padding: EdgeInsets.only(left: 8, top: 0, right: 8, bottom: 0))),
  Positioned(left: 195, top: 196, width: 44, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(2), border: Border.all(color: Color(0xFFD7D7D7), width: 1)), alignment: Alignment.centerLeft, padding: EdgeInsets.only(left: 8, top: 0, right: 8, bottom: 0))),
  Positioned(left: 252, top: 196, width: 44, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(2), border: Border.all(color: Color(0xFFD7D7D7), width: 1)), alignment: Alignment.centerLeft, padding: EdgeInsets.only(left: 8, top: 0, right: 8, bottom: 0))),
  Positioned(left: 309, top: 196, width: 44, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(2), border: Border.all(color: Color(0xFFD7D7D7), width: 1)), alignment: Alignment.centerLeft, padding: EdgeInsets.only(left: 8, top: 0, right: 8, bottom: 0))),
  Positioned(left: 24, top: 114, width: 327, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('验证码已经发送到您的邮箱：38***@163.com ，识别码 QNC重新发送（58s）', textAlign: TextAlign.left, style: TextStyle(fontSize: 12, color: Color(0xFFBFC5CA), height: 1.67), overflow: TextOverflow.visible))),
  Positioned(left: 0, top: 394, width: 375, height: 273, child: Container(width: 375, height: 273, decoration: BoxDecoration(color: Color(0xFFD9D9D9)))),
  Positioned(left: 339, top: 30, width: 24, height: 24, child: Icon(IconData(0xEA91, fontFamily: 'boldIconFont'), size: 24, color: Color(0xFFD7D7D7))),
  Positioned(left: 164, top: 302, width: 48, height: 18, child: SizedBox.shrink()),
]));
  }
}