// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
// ignore_for_file: use_key_in_widget_constructors
// ignore_for_file: file_names, camel_case_types
import 'package:flutter/material.dart';

/// 个人资料 (已绑定)-普通用户 (租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1))
class j7tkJXeMPage extends StatelessWidget {
  const j7tkJXeMPage({super.key});

  @override
  Widget build(BuildContext context) {
return SizedBox(width: 375, height: 920, child: Stack(children: [
  Positioned(left: 0, top: 88, width: 375, height: 54, child: Stack(children: [
Positioned(left: 331, top: 0, width: 20, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 0, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 0, width: 307, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('头像', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 351, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 341, top: 22, width: 10, height: 10, child: Icon(IconData(0xE994, fontFamily: 'boldIconFont'), size: 10, color: Color(0xFFBFC5CA))),
Positioned(left: 311, top: 7, width: 40, height: 40, child: ClipRRect(borderRadius: BorderRadius.circular(100), child: Image.asset('assets/images/41b4fff0-a4e1-11eb-b082-a72ce0a75548.png', fit: BoxFit.contain, width: 40, height: 40)))
])),
  Positioned(left: 24, top: 44, width: 327, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('基础资料', textAlign: TextAlign.left, style: TextStyle(fontSize: 12, color: Color(0xFFAAAAAA), height: 1.67), overflow: TextOverflow.visible))),
  Positioned(left: 0, top: 142, width: 375, height: 54, child: Stack(children: [
Positioned(left: 261, top: 0, width: 90, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('110119114', textAlign: TextAlign.right, style: TextStyle(fontSize: 14, color: Color(0xFFAAAAAA), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 0, width: 237, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('账号', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 351, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0))))
])),
  Positioned(left: 0, top: 196, width: 375, height: 54, child: Stack(children: [
Positioned(left: 291, top: 0, width: 60, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('戴维斯', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFFAAAAAA), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 0, width: 267, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('昵称', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 351, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 341, top: 22, width: 10, height: 10, child: Icon(IconData(0xE994, fontFamily: 'boldIconFont'), size: 10, color: Color(0xFFBFC5CA)))
])),
  Positioned(left: 24, top: 358, width: 327, height: 30, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0), border: Border(bottom: BorderSide(color: Color(0xFFF6F7F8), width: 1))))),
  Positioned(left: 24, top: 404, width: 327, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('第三方账号绑定', textAlign: TextAlign.left, style: TextStyle(fontSize: 12, color: Color(0xFFAAAAAA), height: 1.67), overflow: TextOverflow.visible))),
  Positioned(left: 0, top: 502, width: 375, height: 54, child: Stack(children: [
Positioned(left: 24, top: 30, width: 267, height: 24, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('未绑定', textAlign: TextAlign.left, style: TextStyle(fontSize: 12, color: Color(0xFF7F8B96), height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 291, top: 0, width: 60, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('去绑定', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFFFC2B31), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 0, width: 267, height: 30, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('Google+', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 351, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 341, top: 22, width: 10, height: 10, child: Icon(IconData(0xE994, fontFamily: 'boldIconFont'), size: 10, color: Color(0xFFBFC5CA)))
])),
  Positioned(left: 24, top: 610, width: 327, height: 30, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0), border: Border(bottom: BorderSide(color: Color(0xFFF6F7F8), width: 1))))),
  Positioned(left: 24, top: 656, width: 327, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('密保资料', textAlign: TextAlign.left, style: TextStyle(fontSize: 12, color: Color(0xFFAAAAAA), height: 1.67), overflow: TextOverflow.visible))),
  Positioned(left: 0, top: 754, width: 375, height: 54, child: Stack(children: [
Positioned(left: 291, top: 0, width: 60, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('去绑定', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFFFC2B31), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 0, width: 267, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('邮箱', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 351, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 341, top: 22, width: 10, height: 10, child: Icon(IconData(0xE994, fontFamily: 'boldIconFont'), size: 10, color: Color(0xFFBFC5CA)))
])),
  Positioned(left: 0, top: 808, width: 375, height: 54, child: Stack(children: [
Positioned(left: 291, top: 0, width: 60, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 0, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 0, width: 267, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('账号安全', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 351, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 341, top: 22, width: 10, height: 10, child: Icon(IconData(0xE994, fontFamily: 'boldIconFont'), size: 10, color: Color(0xFFBFC5CA)))
])),
  Positioned(left: 0, top: 250, width: 375, height: 54, child: Stack(children: [
Positioned(left: 291, top: 0, width: 60, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('男', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFFAAAAAA), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 0, width: 267, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('性别', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 351, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 341, top: 22, width: 10, height: 10, child: Icon(IconData(0xE994, fontFamily: 'boldIconFont'), size: 10, color: Color(0xFFBFC5CA)))
])),
  Positioned(left: 0, top: 304, width: 375, height: 54, child: Stack(children: [
Positioned(left: 291, top: 0, width: 60, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('18', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFFAAAAAA), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 0, width: 267, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('年龄', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 351, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 341, top: 22, width: 10, height: 10, child: Icon(IconData(0xE994, fontFamily: 'boldIconFont'), size: 10, color: Color(0xFFBFC5CA)))
])),
  Positioned(left: 24, top: 0, width: 327, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
  Positioned(left: 0, top: 448, width: 375, height: 54, child: Stack(children: [
Positioned(left: 24, top: 30, width: 267, height: 24, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('未绑定', textAlign: TextAlign.left, style: TextStyle(fontSize: 12, color: Color(0xFF7F8B96), height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 291, top: 0, width: 60, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('去绑定', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFFFC2B31), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 0, width: 267, height: 30, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('Facebook', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 351, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 341, top: 22, width: 10, height: 10, child: Icon(IconData(0xE994, fontFamily: 'boldIconFont'), size: 10, color: Color(0xFFBFC5CA)))
])),
  Positioned(left: 0, top: 700, width: 375, height: 54, child: Stack(children: [
Positioned(left: 291, top: 0, width: 60, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('去绑定', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFFFC2B31), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 0, width: 267, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('手机号', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 351, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 341, top: 22, width: 10, height: 10, child: Icon(IconData(0xE994, fontFamily: 'boldIconFont'), size: 10, color: Color(0xFFBFC5CA)))
])),
  Positioned(left: 57.7, top: 861.9, width: 260, height: 40, child: Container(decoration: BoxDecoration(color: Color(0xFF000000), borderRadius: BorderRadius.circular(10)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('原型：查看已绑定状态', textAlign: TextAlign.center, style: TextStyle(fontSize: 16, color: Color(0xFFFFFFFF), height: 1.25), overflow: TextOverflow.visible))),
  Positioned(left: 0, top: 556, width: 375, height: 54, child: Stack(children: [
Positioned(left: 24, top: 30, width: 267, height: 24, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('未绑定', textAlign: TextAlign.left, style: TextStyle(fontSize: 12, color: Color(0xFF7F8B96), height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 291, top: 0, width: 60, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('去绑定', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFFFC2B31), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 0, width: 267, height: 30, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('Apple', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 351, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 341, top: 22, width: 10, height: 10, child: Icon(IconData(0xE994, fontFamily: 'boldIconFont'), size: 10, color: Color(0xFFBFC5CA)))
])),
]));
  }
}