// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
// ignore_for_file: use_key_in_widget_constructors
// ignore_for_file: file_names, camel_case_types
import 'package:flutter/material.dart';

/// 性别修改/设置 (租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1))
class jzTpcP3dzD0Page extends StatelessWidget {
  const jzTpcP3dzD0Page({super.key});

  @override
  Widget build(BuildContext context) {
return SizedBox(width: 375, height: 667, child: Stack(children: [
  Positioned(left: 0, top: 20, width: 375, height: 44, child: Stack(children: [
Positioned(left: 44, top: 0, width: 287, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('个人资料', textAlign: TextAlign.center, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 0, width: 16, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 16, top: 0, width: 28, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 359, top: 0, width: 16, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 331, top: 0, width: 28, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 14, width: 16, height: 16, child: Icon(IconData(0xE998, fontFamily: 'boldIconFont'), size: 16, color: Color(0xFF000000))),
Positioned(left: 0, top: 0, width: 44, height: 44, child: SizedBox.shrink())
])),
  Positioned(left: 0, top: 0, width: 375, height: 20, child: Stack(children: [
Positioned(left: 0, top: 0, width: 375, height: 20, child: Stack(children: [
Positioned(left: 0, top: 0, width: 375, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), alignment: Alignment.centerLeft, padding: EdgeInsets.only(left: 6, top: 0, right: 8, bottom: 0))),
Positioned(left: 349, top: 2, width: 16, height: 16, child: Icon(IconData(0xEB08, fontFamily: 'lightIconFont'), size: 16, color: Color(0xFF333333))),
Positioned(left: 45, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E8, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333))),
Positioned(left: 305, top: 6, width: 8, height: 8, child: Icon(IconData(0xEB10, fontFamily: 'lightIconFont'), size: 8, color: Color(0xFF333333))),
Positioned(left: 73, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E7, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333))),
Positioned(left: 6, top: 7, width: 30, height: 5, child: Stack(children: [
Positioned(left: 0, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 6, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 13, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 19, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 25, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1F, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF7F7F7F)))
])),
Positioned(left: 318, top: 5, width: 26, height: 10, child: SizedBox.shrink()),
Positioned(left: 59, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E8, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333)))
]))
])),
  Positioned(left: 0, top: 117, width: 375, height: 54, child: Stack(children: [
Positioned(left: 331, top: 0, width: 20, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 0, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 0, width: 307, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('头像', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 351, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 341, top: 22, width: 10, height: 10, child: Icon(IconData(0xE994, fontFamily: 'boldIconFont'), size: 10, color: Color(0xFFBFC5CA))),
Positioned(left: 311, top: 7, width: 40, height: 40, child: ClipRRect(borderRadius: BorderRadius.circular(100), child: Image.asset('assets/images/41b4fff0-a4e1-11eb-b082-a72ce0a75548.png', fit: BoxFit.contain, width: 40, height: 40)))
])),
  Positioned(left: 24, top: 73, width: 327, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('基础资料', textAlign: TextAlign.left, style: TextStyle(fontSize: 12, color: Color(0xFFAAAAAA), height: 1.67), overflow: TextOverflow.visible))),
  Positioned(left: 0, top: 171, width: 375, height: 54, child: Stack(children: [
Positioned(left: 261, top: 0, width: 90, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('110119114', textAlign: TextAlign.right, style: TextStyle(fontSize: 14, color: Color(0xFFAAAAAA), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 0, width: 237, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('账号', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 351, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0))))
])),
  Positioned(left: 0, top: 225, width: 375, height: 54, child: Stack(children: [
Positioned(left: 291, top: 0, width: 60, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('戴维斯', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFFAAAAAA), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 0, width: 267, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('昵称', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 351, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 341, top: 22, width: 10, height: 10, child: Icon(IconData(0xE994, fontFamily: 'boldIconFont'), size: 10, color: Color(0xFFBFC5CA)))
])),
  Positioned(left: 0, top: 279, width: 375, height: 54, child: Stack(children: [
Positioned(left: 291, top: 0, width: 60, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('男', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFFAAAAAA), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 0, width: 267, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('性别', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 351, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 341, top: 22, width: 10, height: 10, child: Icon(IconData(0xE994, fontFamily: 'boldIconFont'), size: 10, color: Color(0xFFBFC5CA)))
])),
  Positioned(left: 0, top: 333, width: 375, height: 54, child: Stack(children: [
Positioned(left: 291, top: 0, width: 60, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('18', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFFAAAAAA), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 0, width: 267, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('年龄', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 351, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 341, top: 22, width: 10, height: 10, child: Icon(IconData(0xE994, fontFamily: 'boldIconFont'), size: 10, color: Color(0xFFBFC5CA)))
])),
  Positioned(left: 0, top: 0, width: 375, height: 667, child: Container(decoration: BoxDecoration(color: Color(0x4C000000), borderRadius: BorderRadius.circular(0)))),
  Positioned(left: 0, top: 397, width: 375, height: 270, child: Stack(children: [
Positioned.fill(child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.only(topLeft: Radius.circular(24), topRight: Radius.circular(24), bottomRight: Radius.circular(0), bottomLeft: Radius.circular(0))))),
Positioned(left: 0, top: 0, width: 375, height: 82, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.only(topLeft: Radius.circular(32), topRight: Radius.circular(32), bottomRight: Radius.circular(0), bottomLeft: Radius.circular(0))), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('性别', textAlign: TextAlign.center, style: TextStyle(fontSize: 16, color: Color(0xFF333333), fontWeight: FontWeight.w700, height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 82, width: 375, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFA6DAD6)), padding: EdgeInsets.only(left: 24, right: 0, top: 0, bottom: 0), child: Text('男', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFF333333), fontWeight: FontWeight.w700, height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 136, width: 375, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF)), padding: EdgeInsets.only(left: 24, right: 0, top: 0, bottom: 0), child: Text('女', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFF333333), fontWeight: FontWeight.w700, height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 190, width: 375, height: 80, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF)))),
Positioned(left: 205, top: 190, width: 154, height: 48, child: Stack(children: [
Positioned.fill(child: Container(decoration: BoxDecoration(color: Color(0xFF3EB5AE), borderRadius: BorderRadius.circular(24)))),
Positioned(left: 63, top: 16, width: 28, height: 16, child: Text('确定', textAlign: TextAlign.left, overflow: TextOverflow.visible))
])),
Positioned(left: 17, top: 190, width: 154, height: 48, child: Stack(children: [
Positioned.fill(child: Container(decoration: BoxDecoration(color: Color(0xFFF6F7F8), borderRadius: BorderRadius.circular(24)))),
Positioned(left: 63, top: 16, width: 28, height: 16, child: Text('取消', textAlign: TextAlign.left, overflow: TextOverflow.visible))
]))
])),
]));
  }
}