// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
// ignore_for_file: use_key_in_widget_constructors
// ignore_for_file: file_names, camel_case_types
import 'package:flutter/material.dart';

/// 协议勾选弹窗 (租户-APP端)
class kH54yzCdPage extends StatelessWidget {
  const kH54yzCdPage({super.key});

  @override
  Widget build(BuildContext context) {
return SizedBox(width: 962, height: 1080, child: Stack(children: [
  Positioned(left: 48, top: 74, width: 375, height: 667, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0), border: Border.all(color: Color(0xFF797979), width: 1)))),
  Positioned(left: -448, top: 74, width: 375, height: 798, child: ClipRRect(borderRadius: BorderRadius.circular(0), child: Image.asset('assets/images/05927330-1267-11ef-996e-ab0435ed0330.png', fit: BoxFit.contain, width: 375, height: 798))),
  Positioned(left: 48, top: 74, width: 375, height: 667, child: Container(decoration: BoxDecoration(color: Color(0x4A000000), borderRadius: BorderRadius.circular(0)))),
  Positioned(left: 86, top: 307, width: 300, height: 173, child: Stack(children: [
Positioned.fill(child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(4), boxShadow: [BoxShadow(color: Color(0x26000000), blurRadius: 6, offset: Offset(0, 3))]))),
Positioned(left: 18, top: 130, width: 110, height: 30, child: Stack(children: [
Positioned.fill(child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(15), border: Border.all(color: Color(0xFFF2F2F2), width: 1)))),
Positioned(left: 27, top: 6.5, width: 56, height: 17, child: Text('我再想想', textAlign: TextAlign.left, overflow: TextOverflow.visible))
])),
Positioned(left: 168, top: 130, width: 110, height: 30, child: Stack(children: [
Positioned.fill(child: Container(decoration: BoxDecoration(color: Color(0xFF000000), borderRadius: BorderRadius.circular(15)))),
Positioned(left: 41, top: 6.5, width: 28, height: 17, child: Text('同意', textAlign: TextAlign.left, overflow: TextOverflow.visible))
])),
Positioned(left: 0, top: 23, width: 300, height: 74, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 32, right: 32, top: 0, bottom: 0), child: Text('请阅读并同意《隐私政策》《用户服务协议》', textAlign: TextAlign.left, style: TextStyle(color: Color(0xFF7F7F7F)), overflow: TextOverflow.visible)))
])),
  Positioned(left: 461.6, top: 360.4, width: 221, height: 142, child: SizedBox.shrink()),
]));
  }
}