// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
// ignore_for_file: use_key_in_widget_constructors
// ignore_for_file: file_names, camel_case_types
import 'package:flutter/material.dart';

/// APP登录时检测到账号被冻结(弹窗) (租户-APP端/会员端登录(APP))
class KIdMBIJQC2mPage extends StatelessWidget {
  const KIdMBIJQC2mPage({super.key});

  @override
  Widget build(BuildContext context) {
return SizedBox(width: 375, height: 667, child: Stack(children: [
  Positioned(left: 0, top: 0, width: 375, height: 667, child: Container(decoration: BoxDecoration(color: Color(0x997E7F80), borderRadius: BorderRadius.circular(0)))),
  Positioned(left: 38, top: 247, width: 300, height: 173, child: Stack(children: [
Positioned.fill(child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(4), boxShadow: [BoxShadow(color: Color(0x26000000), blurRadius: 6, offset: Offset(0, 3))]))),
Positioned(left: 18, top: 130, width: 110, height: 30, child: Stack(children: [
Positioned.fill(child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(15), border: Border.all(color: Color(0xFFF2F2F2), width: 1)))),
Positioned(left: 41, top: 6.5, width: 28, height: 17, child: Text('取消', textAlign: TextAlign.left, overflow: TextOverflow.visible))
])),
Positioned(left: 168, top: 130, width: 110, height: 30, child: Stack(children: [
Positioned.fill(child: Container(decoration: BoxDecoration(color: Color(0xFF000000), borderRadius: BorderRadius.circular(15)))),
Positioned(left: 27, top: 6.5, width: 56, height: 17, child: Text('联系客服', textAlign: TextAlign.left, overflow: TextOverflow.visible))
])),
Positioned(left: 0, top: 15, width: 300, height: 74, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 32, right: 32, top: 0, bottom: 0), child: Text('账号被冻结您的账号被系统冻结，请尽快联系客服解除冻结状态', textAlign: TextAlign.left, style: TextStyle(fontWeight: FontWeight.w700), overflow: TextOverflow.visible)))
])),
]));
  }
}