// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
// ignore_for_file: use_key_in_widget_constructors
// ignore_for_file: file_names, camel_case_types
import 'package:flutter/material.dart';

/// 选择手机号归属地 (租户-APP端)
class nJ1cwHfpPage extends StatelessWidget {
  const nJ1cwHfpPage({super.key});

  @override
  Widget build(BuildContext context) {
return SizedBox(width: 535, height: 1080, child: Stack(children: [
  Positioned(left: 84, top: 102, width: 367, height: 785, child: ClipRRect(borderRadius: BorderRadius.circular(0), child: Image.asset('assets/images/3a0f5850-39b6-11ef-8049-69d89b4e38f0.png', fit: BoxFit.contain, width: 367, height: 785))),
]));
  }
}