// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
// ignore_for_file: use_key_in_widget_constructors
// ignore_for_file: file_names, camel_case_types
import 'package:flutter/material.dart';

/// 第三方登录页面（账号未登录状态） (租户-APP端/终端用户注册(APP)/第三方授权注册)
class n7GYOc85noRPage extends StatelessWidget {
  const n7GYOc85noRPage({super.key});

  @override
  Widget build(BuildContext context) {
return SizedBox(width: 375, height: 667, child: Stack(children: [
  Positioned(left: 113, top: 244, width: 150, height: 180, child: ColoredBox(color: Color(0xFFFFDF25))),
  Positioned(left: 432, top: 0, width: 375, height: 1006, child: ClipRRect(borderRadius: BorderRadius.circular(0), child: Image.asset('assets/images/1746ed40-a654-11eb-a7d7-6db06b4eff67.png', fit: BoxFit.contain, width: 375, height: 1006))),
  Positioned(left: 0, top: 0, width: 375, height: 20, child: Stack(children: [
Positioned(left: 0, top: 0, width: 375, height: 20, child: Stack(children: [
Positioned(left: 0, top: 0, width: 375, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), alignment: Alignment.centerLeft, padding: EdgeInsets.only(left: 6, top: 0, right: 8, bottom: 0))),
Positioned(left: 349, top: 2, width: 16, height: 16, child: Icon(IconData(0xEB08, fontFamily: 'lightIconFont'), size: 16, color: Color(0xFF333333))),
Positioned(left: 45, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E8, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333))),
Positioned(left: 305, top: 6, width: 8, height: 8, child: Icon(IconData(0xEB10, fontFamily: 'lightIconFont'), size: 8, color: Color(0xFF333333))),
Positioned(left: 73, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E7, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333))),
Positioned(left: 6, top: 7, width: 30, height: 5, child: Stack(children: [
Positioned(left: 0, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 6, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 13, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 19, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 25, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1F, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF7F7F7F)))
])),
Positioned(left: 318, top: 5, width: 26, height: 10, child: SizedBox.shrink()),
Positioned(left: 59, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E8, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333)))
]))
])),
  Positioned(left: 0, top: 20, width: 375, height: 44, child: Stack(children: [
Positioned(left: 44, top: 0, width: 255, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 0, top: 0, width: 16, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 16, top: 0, width: 28, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 359, top: 0, width: 16, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 299, top: 0, width: 60, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('中国大陆', textAlign: TextAlign.center, style: TextStyle(fontSize: 12, color: Color(0xFF3EB5AE), height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 24, top: 14, width: 16, height: 16, child: Icon(IconData(0xE998, fontFamily: 'boldIconFont'), size: 16, color: Color(0xFF000000))),
Positioned(left: 0, top: 0, width: 44, height: 44, child: SizedBox.shrink())
])),
  Positioned(left: 58, top: 457, width: 260, height: 40, child: Container(decoration: BoxDecoration(color: Color(0xFF000000), borderRadius: BorderRadius.circular(20)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('已关联账号 - 登录成功', textAlign: TextAlign.center, style: TextStyle(fontSize: 14, color: Color(0xFFFFFFFF), height: 1.43), overflow: TextOverflow.visible))),
  Positioned(left: 58, top: 513, width: 260, height: 40, child: Container(decoration: BoxDecoration(color: Color(0xFF000000), borderRadius: BorderRadius.circular(10)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('未关联账号(例:Facebook)-登录成功', textAlign: TextAlign.center, style: TextStyle(fontSize: 12, color: Color(0xFFFFFFFF), height: 1.67), overflow: TextOverflow.visible))),
]));
  }
}