// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
// ignore_for_file: use_key_in_widget_constructors
// ignore_for_file: file_names, camel_case_types
import 'package:flutter/material.dart';

/// Google+添加绑定 (租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/账号关联/Google+绑定/解绑)
class OgYamrXEFalPage extends StatelessWidget {
  const OgYamrXEFalPage({super.key});

  @override
  Widget build(BuildContext context) {
return SizedBox(width: 375, height: 667, child: Stack(children: [
  Positioned(left: 113, top: 244, width: 150, height: 180, child: ColoredBox(color: Color(0xFFFFDF25))),
]));
  }
}