// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
// ignore_for_file: use_key_in_widget_constructors
// ignore_for_file: file_names, camel_case_types
import 'package:flutter/material.dart';

/// 账号安全 (租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1))
class q9bt3PbzK8Page extends StatelessWidget {
  const q9bt3PbzK8Page({super.key});

  @override
  Widget build(BuildContext context) {
return SizedBox(width: 375, height: 667, child: Stack(children: [
  Positioned(left: 0, top: 8, width: 375, height: 78, child: Container(decoration: BoxDecoration(color: Color(0xFF000000), borderRadius: BorderRadius.circular(0)))),
  Positioned(left: 30, top: 26, width: 30, height: 30, child: ClipRRect(borderRadius: BorderRadius.circular(50), child: Image.asset('assets/images/f00a82a0-2a6b-11eb-9d07-2f4793ff081d.jpg', fit: BoxFit.contain, width: 30, height: 30))),
  Positioned(left: 74, top: 29, width: 227, height: 24, child: SizedBox.shrink()),
  Positioned(left: 24, top: 286, width: 160, height: 100, child: Stack(children: [
Positioned(left: 0, top: 0, width: 160, height: 100, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 30), child: Text('设备管理', textAlign: TextAlign.center, style: TextStyle(fontSize: 14, color: Color(0xCC000000), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 10, top: 6, width: 140, height: 88, child: Container(decoration: BoxDecoration(color: Color(0x8080D3F8), borderRadius: BorderRadius.circular(2)))),
Positioned(left: 0, top: 68, width: 160, height: 32, child: Container(padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('管理您当前登陆的设备', textAlign: TextAlign.center, style: TextStyle(fontSize: 12, color: Color(0xFFAAAAAA), height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 68.4, top: 20, width: 24, height: 24, child: Icon(IconData(0xE86C, fontFamily: 'boldIconFont'), size: 24, color: Color(0xFFD8001B)))
])),
  Positioned(left: 24, top: 86, width: 160, height: 100, child: Stack(children: [
Positioned(left: 0, top: 0, width: 160, height: 100, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 30), child: Text('修改密码', textAlign: TextAlign.center, style: TextStyle(fontSize: 14, color: Color(0xCC000000), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 10, top: 6, width: 140, height: 88, child: Container(decoration: BoxDecoration(color: Color(0x8080D3F8), borderRadius: BorderRadius.circular(2)))),
Positioned(left: 68.4, top: 21, width: 24, height: 24, child: Icon(IconData(0xE84A, fontFamily: 'boldIconFont'), size: 24, color: Color(0xFFF3C756))),
Positioned(left: 0, top: 68, width: 160, height: 32, child: Container(padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('上次修改:  2020-09-08', textAlign: TextAlign.center, style: TextStyle(fontSize: 12, color: Color(0xFFAAAAAA), height: 1.67), overflow: TextOverflow.visible)))
])),
  Positioned(left: 191, top: 86, width: 160, height: 100, child: Stack(children: [
Positioned(left: 0, top: 0, width: 160, height: 100, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 30), child: Text('修改绑定手机', textAlign: TextAlign.center, style: TextStyle(fontSize: 14, color: Color(0xCC000000), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 10, top: 6, width: 140, height: 88, child: Container(decoration: BoxDecoration(color: Color(0x8080D3F8), borderRadius: BorderRadius.circular(2)))),
Positioned(left: 68.4, top: 20, width: 24, height: 24, child: Icon(IconData(0xEAFB, fontFamily: 'boldIconFont'), size: 24, color: Color(0xFF9775DE))),
Positioned(left: 1, top: 68, width: 158, height: 32, child: Container(padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('当前绑定:  139****0728', textAlign: TextAlign.center, style: TextStyle(fontSize: 12, color: Color(0xFFAAAAAA), height: 1.67), overflow: TextOverflow.visible)))
])),
  Positioned(left: 191, top: 186, width: 160, height: 100, child: Stack(children: [
Positioned(left: 0, top: 0, width: 160, height: 100, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 30), child: Text('账号关联', textAlign: TextAlign.center, style: TextStyle(fontSize: 14, color: Color(0xCC000000), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 10, top: 6, width: 140, height: 88, child: Container(decoration: BoxDecoration(color: Color(0x8080D3F8), borderRadius: BorderRadius.circular(2)))),
Positioned(left: 0, top: 68, width: 160, height: 32, child: Container(padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('可使用第三方账号登陆APP', textAlign: TextAlign.center, style: TextStyle(fontSize: 12, color: Color(0xFFAAAAAA), height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 68.4, top: 24, width: 24, height: 24, child: Icon(IconData(0xE8EC, fontFamily: 'boldIconFont'), size: 24, color: Color(0xFF007EB4)))
])),
  Positioned(left: 24, top: 186, width: 160, height: 100, child: Stack(children: [
Positioned(left: 0, top: 0, width: 160, height: 100, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 30), child: Text('修改绑定邮箱', textAlign: TextAlign.center, style: TextStyle(fontSize: 14, color: Color(0xCC000000), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 10, top: 6, width: 140, height: 88, child: Container(decoration: BoxDecoration(color: Color(0x8080D3F8), borderRadius: BorderRadius.circular(2)))),
Positioned(left: 68.4, top: 21, width: 24, height: 24, child: Icon(IconData(0xEBA0, fontFamily: 'boldIconFont'), size: 24, color: Color(0xFF65CD8C))),
Positioned(left: 0, top: 68, width: 160, height: 32, child: Container(padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('a***72@163.com', textAlign: TextAlign.center, style: TextStyle(fontSize: 12, color: Color(0xFFAAAAAA), height: 1.67), overflow: TextOverflow.visible)))
])),
  Positioned(left: 53.9, top: 467.3, width: 260, height: 40, child: Container(decoration: BoxDecoration(color: Color(0xFF000000), borderRadius: BorderRadius.circular(10)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('原型：查看未关联状态', textAlign: TextAlign.center, style: TextStyle(fontSize: 16, color: Color(0xFFFFFFFF), height: 1.25), overflow: TextOverflow.visible))),
  Positioned(left: 191, top: 284, width: 160, height: 100, child: Stack(children: [
Positioned(left: 0, top: 0, width: 160, height: 100, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 30), child: Text('账号日志', textAlign: TextAlign.center, style: TextStyle(fontSize: 14, color: Color(0xCC000000), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 10, top: 4, width: 140, height: 88, child: Container(decoration: BoxDecoration(color: Color(0x8080D3F8), borderRadius: BorderRadius.circular(2)))),
Positioned(left: 0, top: 68, width: 160, height: 32, child: Container(padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('查看账号登录日志', textAlign: TextAlign.center, style: TextStyle(fontSize: 12, color: Color(0xFFAAAAAA), height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 68, top: 24, width: 24, height: 24, child: Icon(IconData(0xEBD7, fontFamily: 'boldIconFont'), size: 24, color: Color(0xFFF59B22)))
])),
]));
  }
}