// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
// ignore_for_file: use_key_in_widget_constructors
// ignore_for_file: file_names, camel_case_types
import 'package:flutter/material.dart';

/// APP选择(站点)国家&地区-弹窗 (租户-PC端/注册 登录 找回密码 切换账号/站点切换登录(未设计)/APP/H5)
class TUst4HcH0iLPage extends StatelessWidget {
  const TUst4HcH0iLPage({super.key});

  @override
  Widget build(BuildContext context) {
return SizedBox(width: 375, height: 667, child: Stack(children: [
  Positioned(left: -1166, top: 20, width: 375, height: 813, child: ClipRRect(borderRadius: BorderRadius.circular(0), child: Image.asset('assets/images/69aec480-cc1a-11ec-8980-db9ad207c083.jpg', fit: BoxFit.contain, width: 375, height: 813))),
  Positioned(left: 0, top: 0, width: 375, height: 20, child: Stack(children: [
Positioned(left: 0, top: 0, width: 375, height: 20, child: Stack(children: [
Positioned(left: 0, top: 0, width: 375, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), alignment: Alignment.centerLeft, padding: EdgeInsets.only(left: 6, top: 0, right: 8, bottom: 0))),
Positioned(left: 349, top: 2, width: 16, height: 16, child: Icon(IconData(0xEB08, fontFamily: 'lightIconFont'), size: 16, color: Color(0xFF333333))),
Positioned(left: 45, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E8, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333))),
Positioned(left: 305, top: 6, width: 8, height: 8, child: Icon(IconData(0xEB10, fontFamily: 'lightIconFont'), size: 8, color: Color(0xFF333333))),
Positioned(left: 73, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E7, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333))),
Positioned(left: 6, top: 7, width: 30, height: 5, child: Stack(children: [
Positioned(left: 0, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 6, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 13, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 19, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 25, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1F, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF7F7F7F)))
])),
Positioned(left: 318, top: 5, width: 26, height: 10, child: SizedBox.shrink()),
Positioned(left: 59, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E8, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333)))
]))
])),
  Positioned(left: 0, top: 0, width: 375, height: 667, child: Container(decoration: BoxDecoration(color: Color(0x997E7F80), borderRadius: BorderRadius.circular(0)))),
  Positioned(left: 20, top: 20, width: 335, height: 627, child: Stack(children: [
Positioned.fill(child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(12)))),
Positioned(left: 0, top: 0, width: 335, height: 64, child: Container(decoration: BoxDecoration(border: Border(bottom: BorderSide(color: Color(0xFFD7D7D7), width: 1))), alignment: Alignment.centerLeft, padding: EdgeInsets.only(left: 64, top: 0, right: 8, bottom: 0), child: Text('搜索国家&地区', style: TextStyle(fontSize: 14, color: Color(0xFF333333)), overflow: TextOverflow.ellipsis))),
Positioned(left: 0, top: 208, width: 335, height: 48, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 40, right: 0, top: 0, bottom: 0), child: Text('Ghana', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFF333333), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 10, top: 220, width: 24, height: 24, child: ClipRRect(borderRadius: BorderRadius.circular(0), child: Image.asset('assets/images/29433460-cc21-11ec-9fcb-ede013bc170a.png', fit: BoxFit.contain, width: 24, height: 24))),
Positioned(left: 0, top: 256, width: 335, height: 48, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 40, right: 0, top: 0, bottom: 0), child: Text('Uganda', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFF333333), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 10, top: 268, width: 24, height: 24, child: ClipRRect(borderRadius: BorderRadius.circular(0), child: Image.asset('assets/images/29433460-cc21-11ec-9fcb-ede013bc170a.png', fit: BoxFit.contain, width: 24, height: 24))),
Positioned(left: 0, top: 304, width: 335, height: 48, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 40, right: 0, top: 0, bottom: 0), child: Text('Tanzania', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFF333333), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 10, top: 316, width: 24, height: 24, child: ClipRRect(borderRadius: BorderRadius.circular(0), child: Image.asset('assets/images/29433460-cc21-11ec-9fcb-ede013bc170a.png', fit: BoxFit.contain, width: 24, height: 24))),
Positioned(left: 0, top: 352, width: 335, height: 48, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 40, right: 0, top: 0, bottom: 0), child: Text('Benin', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFF333333), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 10, top: 364, width: 24, height: 24, child: ClipRRect(borderRadius: BorderRadius.circular(0), child: Image.asset('assets/images/29433460-cc21-11ec-9fcb-ede013bc170a.png', fit: BoxFit.contain, width: 24, height: 24))),
Positioned(left: 0, top: 400, width: 335, height: 48, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 40, right: 0, top: 0, bottom: 0), child: Text('Brazil', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFF333333), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 10, top: 412, width: 24, height: 24, child: ClipRRect(borderRadius: BorderRadius.circular(0), child: Image.asset('assets/images/29433460-cc21-11ec-9fcb-ede013bc170a.png', fit: BoxFit.contain, width: 24, height: 24))),
Positioned(left: 0, top: 448, width: 335, height: 48, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 40, right: 0, top: 0, bottom: 0), child: Text('Chile', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFF333333), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 10, top: 460, width: 24, height: 24, child: ClipRRect(borderRadius: BorderRadius.circular(0), child: Image.asset('assets/images/29433460-cc21-11ec-9fcb-ede013bc170a.png', fit: BoxFit.contain, width: 24, height: 24))),
Positioned(left: 0, top: 496, width: 335, height: 48, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 40, right: 0, top: 0, bottom: 0), child: Text('Cote d Ivoire', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFF333333), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 10, top: 508, width: 24, height: 24, child: ClipRRect(borderRadius: BorderRadius.circular(0), child: Image.asset('assets/images/29433460-cc21-11ec-9fcb-ede013bc170a.png', fit: BoxFit.contain, width: 24, height: 24))),
Positioned(left: 0, top: 544, width: 335, height: 48, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 40, right: 0, top: 0, bottom: 0), child: Text('Congo', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFF333333), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 10, top: 556, width: 24, height: 24, child: ClipRRect(borderRadius: BorderRadius.circular(0), child: Image.asset('assets/images/29433460-cc21-11ec-9fcb-ede013bc170a.png', fit: BoxFit.contain, width: 24, height: 24))),
Positioned(left: 0, top: 160, width: 335, height: 48, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 12, right: 0, top: 0, bottom: 0), child: Text('国家或地区(A-Z)', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFFD7D7D7), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 24, top: 22, width: 20, height: 20, child: Icon(IconData(0xE8D1, fontFamily: 'boldIconFont'), size: 20, color: Color(0xFF000000))),
Positioned(left: 0, top: 64, width: 335, height: 48, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 40, right: 0, top: 0, bottom: 0), child: Text('Ghana', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFF333333), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 10, top: 76, width: 24, height: 24, child: ClipRRect(borderRadius: BorderRadius.circular(0), child: Image.asset('assets/images/29433460-cc21-11ec-9fcb-ede013bc170a.png', fit: BoxFit.contain, width: 24, height: 24))),
Positioned(left: 0, top: 112, width: 335, height: 48, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 40, right: 0, top: 0, bottom: 0), child: Text('Uganda', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFF333333), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 10, top: 124, width: 24, height: 24, child: ClipRRect(borderRadius: BorderRadius.circular(0), child: Image.asset('assets/images/29433460-cc21-11ec-9fcb-ede013bc170a.png', fit: BoxFit.contain, width: 24, height: 24)))
])),
  Positioned(left: -366, top: 0, width: 303, height: 364, child: ColoredBox(color: Color(0xFFFFDF25))),
  Positioned(left: -767, top: 0, width: 375, height: 813, child: ClipRRect(borderRadius: BorderRadius.circular(0), child: Image.asset('assets/images/7d872e70-cc1a-11ec-8980-db9ad207c083.jpg', fit: BoxFit.contain, width: 375, height: 813))),
]));
  }
}