// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
// ignore_for_file: use_key_in_widget_constructors
// ignore_for_file: file_names, camel_case_types
import 'package:flutter/material.dart';

/// APP切换登录页面 (租户-APP端/切换账户登录(APP))
class VJ0tDnmXUEuPage extends StatelessWidget {
  const VJ0tDnmXUEuPage({super.key});

  @override
  Widget build(BuildContext context) {
return SizedBox(width: 375, height: 667, child: Stack(children: [
  Positioned(left: -606, top: 0, width: 375, height: 813, child: ClipRRect(borderRadius: BorderRadius.circular(0), child: Image.asset('assets/images/eb37b440-cceb-11ec-a4ee-ffb824e4d8d9.jpg', fit: BoxFit.contain, width: 375, height: 813))),
  Positioned(left: 0, top: 0, width: 375, height: 20, child: Stack(children: [
Positioned(left: 0, top: 0, width: 375, height: 20, child: Stack(children: [
Positioned(left: 0, top: 0, width: 375, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), alignment: Alignment.centerLeft, padding: EdgeInsets.only(left: 6, top: 0, right: 8, bottom: 0))),
Positioned(left: 349, top: 2, width: 16, height: 16, child: Icon(IconData(0xEB08, fontFamily: 'lightIconFont'), size: 16, color: Color(0xFF333333))),
Positioned(left: 45, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E8, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333))),
Positioned(left: 305, top: 6, width: 8, height: 8, child: Icon(IconData(0xEB10, fontFamily: 'lightIconFont'), size: 8, color: Color(0xFF333333))),
Positioned(left: 73, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E7, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333))),
Positioned(left: 6, top: 7, width: 30, height: 5, child: Stack(children: [
Positioned(left: 0, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 6, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 13, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 19, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 25, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1F, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF7F7F7F)))
])),
Positioned(left: 318, top: 5, width: 26, height: 10, child: SizedBox.shrink()),
Positioned(left: 59, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E8, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333)))
]))
])),
  Positioned(left: 70, top: 78, width: 244, height: 40, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 8, right: 0, top: 0, bottom: 0), child: Text('Jagrup', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF555555), fontWeight: FontWeight.w700, letterSpacing: 3, height: 1.50), overflow: TextOverflow.visible))),
  Positioned(left: 24, top: 553, width: 327, height: 48, child: Stack(children: [
Positioned.fill(child: Container(decoration: BoxDecoration(color: Color(0xFF000000), borderRadius: BorderRadius.circular(24)))),
Positioned(left: 135.5, top: 15.5, width: 56, height: 17, child: Text('创建账户', textAlign: TextAlign.left, overflow: TextOverflow.visible))
])),
  Transform.rotate(angle: 1.5708, child: Positioned(left: 330, top: 90, width: 16, height: 16, child: Icon(IconData(0xEA52, fontFamily: 'boldIconFont'), size: 16, color: Color(0xFF777777)))),
  Positioned(left: 30, top: 82, width: 32, height: 32, child: Icon(IconData(0xEB57, fontFamily: 'boldIconFont'), size: 32, color: Color(0xFFD7D7D7))),
  Positioned(left: 70, top: 122, width: 244, height: 40, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 8, right: 0, top: 0, bottom: 0), child: Text('账号昵称', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF555555), fontWeight: FontWeight.w700, letterSpacing: 3, height: 1.50), overflow: TextOverflow.visible))),
  Transform.rotate(angle: 1.5708, child: Positioned(left: 330, top: 134, width: 16, height: 16, child: Icon(IconData(0xEA52, fontFamily: 'boldIconFont'), size: 16, color: Color(0xFF777777)))),
  Positioned(left: 30, top: 126, width: 32, height: 32, child: Icon(IconData(0xEB57, fontFamily: 'boldIconFont'), size: 32, color: Color(0xFFD7D7D7))),
  Positioned(left: 70, top: 199, width: 244, height: 24, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 8, right: 0, top: 0, bottom: 0), child: Text('登录另一账户', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFF000000), fontWeight: FontWeight.w700, letterSpacing: 3, height: 1.71), overflow: TextOverflow.visible))),
  Positioned(left: 46, top: 199, width: 24, height: 24, child: Icon(IconData(0xEA61, fontFamily: 'boldIconFont'), size: 24, color: Color(0xFFD7D7D7))),
  Positioned(left: 70, top: 231, width: 244, height: 24, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 8, right: 0, top: 0, bottom: 0), child: Text('找回账户', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFF000000), fontWeight: FontWeight.w700, letterSpacing: 3, height: 1.71), overflow: TextOverflow.visible))),
  Positioned(left: 46, top: 231, width: 24, height: 24, child: Stack(children: [
Positioned(left: 0, top: 0, width: 24, height: 24, child: Container(decoration: BoxDecoration(color: Color(0xFFD7D7D7), borderRadius: BorderRadius.circular(2)))),
Positioned(left: 6, top: 6, width: 12, height: 12, child: Icon(IconData(0xE8DD, fontFamily: 'boldIconFont'), size: 12, color: Color(0xFFFFFFFF)))
])),
  Positioned(left: 411, top: 151, width: 200, height: 120, child: Stack(children: [
Positioned.fill(child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(2), boxShadow: [BoxShadow(color: Color(0xFFD7D7D7), blurRadius: 6, offset: Offset(0, 3))]))),
Positioned(left: 0, top: 0, width: 200, height: 40, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 12, right: 0, top: 0, bottom: 0), child: Text('移除密码', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFF333333), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 40, width: 200, height: 40, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 12, right: 0, top: 0, bottom: 0), child: Text('从设备中移除这个账户', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFF333333), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 80, width: 200, height: 40, child: Container(decoration: BoxDecoration(borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 12, right: 0, top: 0, bottom: 0), child: Text('推送通知免打扰', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFF333333), height: 1.43), overflow: TextOverflow.visible)))
])),
]));
  }
}