// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
// ignore_for_file: use_key_in_widget_constructors
// ignore_for_file: file_names, camel_case_types
import 'package:flutter/material.dart';

/// 个人资料(未绑定) (租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/个人资料 (已绑定)-普通用户)
class wl7u5jqI6tPage extends StatelessWidget {
  const wl7u5jqI6tPage({super.key});

  @override
  Widget build(BuildContext context) {
return SizedBox(width: 375, height: 1000, child: Stack(children: [
  Positioned(left: 0, top: 20, width: 375, height: 44, child: Stack(children: [
Positioned(left: 44, top: 0, width: 287, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('个人资料', textAlign: TextAlign.center, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 0, width: 16, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 16, top: 0, width: 28, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 359, top: 0, width: 16, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 331, top: 0, width: 28, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 14, width: 16, height: 16, child: Icon(IconData(0xE998, fontFamily: 'boldIconFont'), size: 16, color: Color(0xFF000000))),
Positioned(left: 0, top: 0, width: 44, height: 44, child: SizedBox.shrink())
])),
  Positioned(left: 27.6, top: 914.8, width: 320, height: 48, child: Stack(children: [
Positioned.fill(child: Container(decoration: BoxDecoration(color: Color(0xFFF6F7F8), borderRadius: BorderRadius.circular(24)))),
Positioned(left: 132, top: 16, width: 56, height: 16, child: Text('注销登录', textAlign: TextAlign.left, overflow: TextOverflow.visible))
])),
  Positioned(left: 0, top: 0, width: 375, height: 20, child: Stack(children: [
Positioned(left: 0, top: 0, width: 375, height: 20, child: Stack(children: [
Positioned(left: 0, top: 0, width: 375, height: 20, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), alignment: Alignment.centerLeft, padding: EdgeInsets.only(left: 6, top: 0, right: 8, bottom: 0))),
Positioned(left: 349, top: 2, width: 16, height: 16, child: Icon(IconData(0xEB08, fontFamily: 'lightIconFont'), size: 16, color: Color(0xFF333333))),
Positioned(left: 45, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E8, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333))),
Positioned(left: 305, top: 6, width: 8, height: 8, child: Icon(IconData(0xEB10, fontFamily: 'lightIconFont'), size: 8, color: Color(0xFF333333))),
Positioned(left: 73, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E7, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333))),
Positioned(left: 6, top: 7, width: 30, height: 5, child: Stack(children: [
Positioned(left: 0, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 6, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 13, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 19, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1B, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF333333))),
Positioned(left: 25, top: 0, width: 5, height: 5, child: Icon(IconData(0xED1F, fontFamily: 'lightIconFont'), size: 5, color: Color(0xFF7F7F7F)))
])),
Positioned(left: 318, top: 5, width: 26, height: 10, child: SizedBox.shrink()),
Positioned(left: 59, top: 4, width: 11, height: 11, child: Icon(IconData(0xE7E8, fontFamily: 'lightIconFont'), size: 11, color: Color(0xFF333333)))
]))
])),
  Positioned(left: 0, top: 117, width: 375, height: 54, child: Stack(children: [
Positioned(left: 331, top: 0, width: 20, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 0, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 0, width: 307, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('头像', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 351, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 341, top: 22, width: 10, height: 10, child: Icon(IconData(0xE994, fontFamily: 'boldIconFont'), size: 10, color: Color(0xFFBFC5CA))),
Positioned(left: 311, top: 7, width: 40, height: 40, child: ClipRRect(borderRadius: BorderRadius.circular(100), child: Image.asset('assets/images/41b4fff0-a4e1-11eb-b082-a72ce0a75548.png', fit: BoxFit.contain, width: 40, height: 40)))
])),
  Positioned(left: 24, top: 73, width: 327, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('基础资料', textAlign: TextAlign.left, style: TextStyle(fontSize: 12, color: Color(0xFFAAAAAA), height: 1.67), overflow: TextOverflow.visible))),
  Positioned(left: 0, top: 171, width: 375, height: 54, child: Stack(children: [
Positioned(left: 261, top: 0, width: 90, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('110119114', textAlign: TextAlign.right, style: TextStyle(fontSize: 14, color: Color(0xFFAAAAAA), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 0, width: 237, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('账号', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 351, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0))))
])),
  Positioned(left: 0, top: 225, width: 375, height: 54, child: Stack(children: [
Positioned(left: 291, top: 0, width: 60, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('戴维斯', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFFAAAAAA), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 0, width: 267, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('昵称', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 351, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 341, top: 22, width: 10, height: 10, child: Icon(IconData(0xE994, fontFamily: 'boldIconFont'), size: 10, color: Color(0xFFBFC5CA)))
])),
  Positioned(left: 24, top: 387, width: 327, height: 30, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0), border: Border(bottom: BorderSide(color: Color(0xFFF6F7F8), width: 1))))),
  Positioned(left: 24, top: 433, width: 327, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('第三方账号绑定', textAlign: TextAlign.left, style: TextStyle(fontSize: 12, color: Color(0xFFAAAAAA), height: 1.67), overflow: TextOverflow.visible))),
  Positioned(left: 0, top: 531, width: 375, height: 54, child: Stack(children: [
Positioned(left: 24, top: 30, width: 267, height: 24, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('未绑定', textAlign: TextAlign.left, style: TextStyle(fontSize: 12, color: Color(0xFF7F8B96), height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 291, top: 0, width: 60, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('去绑定', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFFFC2B31), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 0, width: 267, height: 30, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('Google+', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 351, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 341, top: 22, width: 10, height: 10, child: Icon(IconData(0xE994, fontFamily: 'boldIconFont'), size: 10, color: Color(0xFFBFC5CA)))
])),
  Positioned(left: 24, top: 639, width: 327, height: 30, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0), border: Border(bottom: BorderSide(color: Color(0xFFF6F7F8), width: 1))))),
  Positioned(left: 24, top: 685, width: 327, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('密保资料', textAlign: TextAlign.left, style: TextStyle(fontSize: 12, color: Color(0xFFAAAAAA), height: 1.67), overflow: TextOverflow.visible))),
  Positioned(left: 0, top: 783, width: 375, height: 54, child: Stack(children: [
Positioned(left: 291, top: 0, width: 60, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('去绑定', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFFFC2B31), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 0, width: 267, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('邮箱', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 351, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 341, top: 22, width: 10, height: 10, child: Icon(IconData(0xE994, fontFamily: 'boldIconFont'), size: 10, color: Color(0xFFBFC5CA)))
])),
  Positioned(left: 0, top: 837, width: 375, height: 54, child: Stack(children: [
Positioned(left: 291, top: 0, width: 60, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 0, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 0, width: 267, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('账号安全', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 351, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 341, top: 22, width: 10, height: 10, child: Icon(IconData(0xE994, fontFamily: 'boldIconFont'), size: 10, color: Color(0xFFBFC5CA)))
])),
  Positioned(left: 0, top: 279, width: 375, height: 54, child: Stack(children: [
Positioned(left: 291, top: 0, width: 60, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('填写', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFFAAAAAA), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 0, width: 267, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('性别', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 351, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 341, top: 22, width: 10, height: 10, child: Icon(IconData(0xE994, fontFamily: 'boldIconFont'), size: 10, color: Color(0xFFBFC5CA)))
])),
  Positioned(left: 0, top: 333, width: 375, height: 54, child: Stack(children: [
Positioned(left: 291, top: 0, width: 60, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('设置', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFFAAAAAA), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 0, width: 267, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('年龄', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 351, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 341, top: 22, width: 10, height: 10, child: Icon(IconData(0xE994, fontFamily: 'boldIconFont'), size: 10, color: Color(0xFFBFC5CA)))
])),
  Positioned(left: 0, top: 477, width: 375, height: 54, child: Stack(children: [
Positioned(left: 24, top: 30, width: 267, height: 24, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('未绑定', textAlign: TextAlign.left, style: TextStyle(fontSize: 12, color: Color(0xFF7F8B96), height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 291, top: 0, width: 60, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('去绑定', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFFFC2B31), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 0, width: 267, height: 30, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('Facebook', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 351, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 341, top: 22, width: 10, height: 10, child: Icon(IconData(0xE994, fontFamily: 'boldIconFont'), size: 10, color: Color(0xFFBFC5CA)))
])),
  Positioned(left: 0, top: 729, width: 375, height: 54, child: Stack(children: [
Positioned(left: 291, top: 0, width: 60, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('去绑定', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFFFC2B31), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 0, width: 267, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('手机号', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 351, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 341, top: 22, width: 10, height: 10, child: Icon(IconData(0xE994, fontFamily: 'boldIconFont'), size: 10, color: Color(0xFFBFC5CA)))
])),
  Positioned(left: 0, top: 585, width: 375, height: 54, child: Stack(children: [
Positioned(left: 24, top: 30, width: 267, height: 24, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('未绑定', textAlign: TextAlign.left, style: TextStyle(fontSize: 12, color: Color(0xFF7F8B96), height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 291, top: 0, width: 60, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('去绑定', textAlign: TextAlign.left, style: TextStyle(fontSize: 14, color: Color(0xFFFC2B31), height: 1.43), overflow: TextOverflow.visible))),
Positioned(left: 0, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 0, width: 267, height: 30, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('Apple', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF000000), height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 351, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 341, top: 22, width: 10, height: 10, child: Icon(IconData(0xE994, fontFamily: 'boldIconFont'), size: 10, color: Color(0xFFBFC5CA)))
])),
]));
  }
}