// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
// ignore_for_file: use_key_in_widget_constructors
// ignore_for_file: file_names, camel_case_types
import 'package:flutter/material.dart';

/// 选择验证方式(修改手机号) (租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/手机号/修改手机号)
class zvkY0mP0xPage extends StatelessWidget {
  const zvkY0mP0xPage({super.key});

  @override
  Widget build(BuildContext context) {
return SizedBox(width: 375, height: 667, child: Stack(children: [
  Positioned(left: 0, top: 108.2, width: 375, height: 54, child: Stack(children: [
Positioned(left: 48, top: 30, width: 283, height: 24, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('验证您绑定的安全手机', textAlign: TextAlign.left, style: TextStyle(fontSize: 12, color: Color(0xFF7F8B96), height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 331, top: 0, width: 20, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 0, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 48, top: 0, width: 283, height: 30, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('通过安全手机接收验证短信', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF000000), fontWeight: FontWeight.w700, height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 351, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 19, width: 16, height: 16, child: Stack(children: [
Positioned(left: 0, top: 0, width: 16, height: 16, child: Container(decoration: BoxDecoration(shape: BoxShape.circle, color: Color(0xFFFFFFFF), border: Border.all(color: Color(0xFF3EB5AE), width: 1)))),
Positioned(left: 3, top: 3, width: 10, height: 10, child: Container(decoration: BoxDecoration(shape: BoxShape.circle, color: Color(0xFF3EB5AE))))
]))
])),
  Positioned(left: 0, top: 162.2, width: 375, height: 54, child: Stack(children: [
Positioned(left: 48, top: 30, width: 283, height: 24, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('验证您绑定的安全邮箱', textAlign: TextAlign.left, style: TextStyle(fontSize: 12, color: Color(0xFF7F8B96), height: 1.67), overflow: TextOverflow.visible))),
Positioned(left: 331, top: 0, width: 20, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 0, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 48, top: 0, width: 283, height: 30, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('通过安全邮箱接收验证邮件', textAlign: TextAlign.left, style: TextStyle(fontSize: 16, color: Color(0xFF000000), fontWeight: FontWeight.w700, height: 1.25), overflow: TextOverflow.visible))),
Positioned(left: 351, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 0, width: 24, height: 54, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)))),
Positioned(left: 24, top: 19, width: 16, height: 16, child: Container(decoration: BoxDecoration(shape: BoxShape.circle, color: Color(0xFFD7D7D7), border: Border.all(color: Color(0xFFD7D7D7), width: 1))))
])),
  Positioned(left: 23.9, top: 64, width: 327, height: 44, child: Container(decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(0)), padding: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 0), child: Text('请选择验证方式：', textAlign: TextAlign.left, style: TextStyle(fontSize: 12, color: Color(0xFFAAAAAA), height: 1.67), overflow: TextOverflow.visible))),
  Positioned(left: 103.9, top: 20, width: 168, height: 20, child: SizedBox.shrink()),
  Positioned(left: 23.9, top: 285, width: 327, height: 48, child: Stack(children: [
Positioned.fill(child: Container(decoration: BoxDecoration(color: Color(0xFF3EB5AE), borderRadius: BorderRadius.circular(24)))),
Positioned(left: 142.5, top: 16, width: 42, height: 16, child: Text('下一步', textAlign: TextAlign.left, overflow: TextOverflow.visible))
])),
]));
  }
}