name: ruoqi_business_app
description: "RuoQi business applications (customer / merchant / partner) on mobile."
resolution: workspace
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  ruoqi_common:
    path: ../../packages/ruoqi_common
  ruoqi_network:
    path: ../../packages/ruoqi_network
  ruoqi_customer_api:
    path: ../../packages/ruoqi_customer_api
  ruoqi_merchant_api:
    path: ../../packages/ruoqi_merchant_api
  ruoqi_partner_api:
    path: ../../packages/ruoqi_partner_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: lightIconFont
      fonts:
        - asset: assets/fonts/lightIconFont.ttf
    - family: boldIconFont
      fonts:
        - asset: assets/fonts/boldIconFont.ttf
