// Generated by tools/rp2flutter/convert.py — do not edit by hand.
import 'package:flutter/material.dart';

import 'prototype_registry.dart';

class PrototypeViewer extends StatelessWidget {
  const PrototypeViewer({super.key, required this.entry});

  final PrototypeEntry entry;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(entry.title),
        actions: [
          Padding(
            padding: const EdgeInsets.only(right: 12),
            child: Center(
              child: Text(
                '${entry.width.toInt()}×${entry.height.toInt()}',
                style: Theme.of(context).textTheme.bodySmall,
              ),
            ),
          ),
        ],
      ),
      body: Center(
        child: InteractiveViewer(
          minScale: 0.1,
          maxScale: 4,
          child: FittedBox(
            fit: BoxFit.scaleDown,
            child: ConstrainedBox(
              constraints: BoxConstraints(
                minWidth: entry.width,
                minHeight: entry.height,
              ),
              child: entry.builder(context),
            ),
          ),
        ),
      ),
    );
  }
}
