// Generated by tools/rp2flutter/convert.py — do not edit by hand.
// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
import 'package:flutter/material.dart';

import 'pages/TUst4HcH0iL.dart';
import 'pages/Fokfbeivniz.dart';
import 'pages/n-J1cwHfp.dart';
import 'pages/k-H54yzCd.dart';
import 'pages/7uwTz_U6aN7.dart';
import 'pages/Zx1sq-Na6W6.dart';
import 'pages/6azDWvwqLZJ.dart';
import 'pages/CmmEnp49pEH.dart';
import 'pages/2XEQbZ0HU_v.dart';
import 'pages/-kGHial-Pge.dart';
import 'pages/2STTxfsewDx.dart';
import 'pages/gnNEa-mfuNT.dart';
import 'pages/J7Ygf3v9_XN.dart';
import 'pages/n7GYOc85noR.dart';
import 'pages/dC-sxuk_oWP.dart';
import 'pages/KIdMBIJQC2m.dart';
import 'pages/cnulI2qsvBQ.dart';
import 'pages/0jIS_efDdcn.dart';
import 'pages/wI65ZFSpGqI.dart';
import 'pages/d4kpcMYob7u.dart';
import 'pages/8oko0Gu4Nx3.dart';
import 'pages/qy6xv_44nUE.dart';
import 'pages/i944FAsAeup.dart';
import 'pages/VJ0tDnmXUEu.dart';
import 'pages/VzWiUuGsAQ-.dart';
import 'pages/cRF08PB7kEe.dart';
import 'pages/SUfHkojkaR0.dart';
import 'pages/E1Oa0Pvm6BO.dart';
import 'pages/j7-t_kJXe-M.dart';
import 'pages/wl7u5jqI6t.dart';
import 'pages/xkgtQlKBMhp.dart';
import 'pages/OzqIWLKP3dJ.dart';
import 'pages/jzTpcP3dzD0.dart';
import 'pages/zvo5uilR6g.dart';
import 'pages/ujecMx2khC8.dart';
import 'pages/j3e2SO5ekKB.dart';
import 'pages/lk7o_Th8qrz.dart';
import 'pages/14r2GOdmpQn.dart';
import 'pages/eQhGzYl1-Zr.dart';
import 'pages/r_zW38BO9Io.dart';
import 'pages/Wpewew-m_lN.dart';
import 'pages/pCkgNT8XRkc.dart';
import 'pages/q9bt3PbzK_8.dart';
import 'pages/6IW2iD_19pL.dart';
import 'pages/KaLiI93JRSt.dart';
import 'pages/tVGZVZBSws0.dart';
import 'pages/iyLcaE8b7zh.dart';
import 'pages/PkpT15R9D5M.dart';
import 'pages/-YoO9wxTxe7.dart';
import 'pages/0Zm8m-yMjMW.dart';
import 'pages/f7gNL47Z-8F.dart';
import 'pages/8Lacvbp1Z7i.dart';
import 'pages/wH77g_uCj9L.dart';
import 'pages/202JJq4djKx.dart';
import 'pages/zv__kY0mP0x.dart';
import 'pages/L8krmiGjCoe.dart';
import 'pages/iP15RTs-U_Q.dart';
import 'pages/rV-454EkgJd.dart';
import 'pages/NONO95E3FsC.dart';
import 'pages/Y8b-Vx2EPPp.dart';
import 'pages/4KkPCCkJ3Of.dart';
import 'pages/Ar-QzgJ9bnH.dart';
import 'pages/ZbE9yFD85IH.dart';
import 'pages/KQ-_vimYB7b.dart';
import 'pages/ts4SlmmlY-G.dart';
import 'pages/7tGZvikV_Xu.dart';
import 'pages/WaRfB42PqyJ.dart';
import 'pages/P2SEC3majPM.dart';
import 'pages/DwoRpBswUK.dart';
import 'pages/OgYamrXEFal.dart';
import 'pages/2qmJIKDW-h-.dart';
import 'pages/unh8-xe9sQ2.dart';
import 'pages/GNiO-0M7VLj.dart';
import 'pages/WHlG1Lu7OA7.dart';
import 'pages/6EyhbjTAFK.dart';
import 'pages/Z519EZPgkYn.dart';
import 'pages/F4wEnb2CNZs.dart';
import 'pages/bEr-OmuCNPK.dart';

class PrototypeFolder {
  const PrototypeFolder(this.name, this.children);
  final String name;
  final List<Object> children;
}

class PrototypeEntry {
  const PrototypeEntry(this.id, this.title, this.path, this.width, this.height, this.builder);
  final String id;
  final String title;
  final String path;
  final double width;
  final double height;
  final WidgetBuilder builder;
}

final List<PrototypeEntry> prototypePages = [
  PrototypeEntry('j3e2SO5ekKB', '修改昵称', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/修改昵称', 375, 667, (_) => j3e2SO5ekKBPage()),
  PrototypeEntry('j7-t_kJXe-M', '个人资料 (已绑定)-普通用户', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/个人资料 (已绑定)-普通用户', 375, 1000, (_) => j7tkJXeMPage()),
  PrototypeEntry('jzTpcP3dzD0', '性别修改/设置', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/性别修改/设置', 375, 667, (_) => jzTpcP3dzD0Page()),
  PrototypeEntry('q9bt3PbzK_8', '账号安全', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全', 375, 667, (_) => q9bt3PbzK8Page()),
  PrototypeEntry('ujecMx2khC8', '头像修改', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/头像修改', 375, 667, (_) => ujecMx2khC8Page()),
  PrototypeEntry('xkgtQlKBMhp', '个人资料-企业用户', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/个人资料-企业用户', 375, 1000, (_) => xkgtQlKBMhpPage()),
  PrototypeEntry('_zvo5uilR6g', '年龄修改/设置', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/年龄修改/设置', 375, 667, (_) => zvo5uilR6gPage()),
  PrototypeEntry('OzqIWLKP3dJ', '个人资料-企业用户 (1)', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/个人资料-企业用户/个人资料-企业用户 (1)', 375, 1000, (_) => OzqIWLKP3dJPage()),
  PrototypeEntry('wl7u5jqI6t_', '个人资料(未绑定)', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/个人资料 (已绑定)-普通用户/个人资料(未绑定)', 375, 1000, (_) => wl7u5jqI6tPage()),
  PrototypeEntry('lk7o_Th8qrz', '手机号绑定', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/手机号绑定/手机号绑定', 375, 667, (_) => lk7oTh8qrzPage()),
  PrototypeEntry('14r2GOdmpQn', '输入验证码', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/手机号绑定/手机号绑定/输入验证码', 375, 667, (_) => P14r2GOdmpQnPage()),
  PrototypeEntry('eQhGzYl1-Zr', '手机号绑定成功页面', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/手机号绑定/手机号绑定/手机号绑定成功页面', 375, 667, (_) => eQhGzYl1ZrPage()),
  PrototypeEntry('7tGZvikV_Xu', '账号关联', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/账号关联', 375, 667, (_) => P7tGZvikVXuPage()),
  PrototypeEntry('F4wEnb2CNZs', '账号日志', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/账号日志', 375, 667, (_) => F4wEnb2CNZsPage()),
  PrototypeEntry('Z519EZPgkYn', '设备管理', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/设备管理', 375, 667, (_) => Z519EZPgkYnPage()),
  PrototypeEntry('6IW2iD_19pL', '新设置密码', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/密码/新设置密码', 375, 667, (_) => P6IW2iD19pLPage()),
  PrototypeEntry('PkpT15R9D5M', '选择验证方式(修改密码)', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/密码/选择验证方式(修改密码)', 375, 667, (_) => PkpT15R9D5MPage()),
  PrototypeEntry('f7gNL47Z-8F', '密码修改成功', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/密码/密码修改成功', 375, 667, (_) => f7gNL47Z8FPage()),
  PrototypeEntry('tVGZVZBSws0', '修改密码（旧密码）', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/密码/修改密码（旧密码）', 375, 667, (_) => tVGZVZBSws0Page()),
  PrototypeEntry('iyLcaE8b7zh', '确认新密码', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/密码/修改密码（旧密码）/确认新密码', 375, 667, (_) => iyLcaE8b7zhPage()),
  PrototypeEntry('KaLiI93JRSt', '密码设置成功', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/密码/新设置密码/密码设置成功', 375, 667, (_) => KaLiI93JRStPage()),
  PrototypeEntry('-YoO9wxTxe7', '手机短信验证', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/密码/选择验证方式(修改密码)/手机短信验证', 375, 667, (_) => YoO9wxTxe7Page()),
  PrototypeEntry('0Zm8m-yMjMW', '邮箱验证', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/密码/选择验证方式(修改密码)/邮箱验证', 375, 667, (_) => P0Zm8myMjMWPage()),
  PrototypeEntry('202JJq4djKx', '修改手机号', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/手机号/修改手机号', 375, 667, (_) => P202JJq4djKxPage()),
  PrototypeEntry('8Lacvbp1Z7i', '新绑定手机号', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/手机号/新绑定手机号', 375, 667, (_) => P8Lacvbp1Z7iPage()),
  PrototypeEntry('rV-454EkgJd', '手机号修改成功', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/手机号/修改手机号/手机号修改成功', 375, 667, (_) => rV454EkgJdPage()),
  PrototypeEntry('zv__kY0mP0x', '选择验证方式(修改手机号)', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/手机号/修改手机号/选择验证方式(修改手机号)', 375, 667, (_) => zvkY0mP0xPage()),
  PrototypeEntry('L8krmiGjCoe', '手机短信验证  (修改手机号)', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/手机号/修改手机号/选择验证方式(修改手机号)/手机短信验证  (修改手机号)', 375, 667, (_) => L8krmiGjCoePage()),
  PrototypeEntry('iP15RTs-U_Q', '邮箱验证 (修改手机号)', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/手机号/修改手机号/选择验证方式(修改手机号)/邮箱验证 (修改手机号)', 375, 667, (_) => iP15RTsUQPage()),
  PrototypeEntry('wH77g_uCj9L', '手机号绑定成功', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/手机号/新绑定手机号/手机号绑定成功', 375, 667, (_) => wH77guCj9LPage()),
  PrototypeEntry('P2SEC3majPM', 'Apple绑定成功页面', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/账号关联/Apple账号绑定/解绑/Apple添加绑定/Apple绑定成功页面', 375, 667, (_) => P2SEC3majPMPage()),
  PrototypeEntry('DwoRpBswUK_', 'Apple解除绑定', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/账号关联/Apple账号绑定/解绑/Apple解除绑定', 375, 667, (_) => DwoRpBswUKPage()),
  PrototypeEntry('WaRfB42PqyJ', 'Apple添加绑定', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/账号关联/Apple账号绑定/解绑/Apple添加绑定', 375, 667, (_) => WaRfB42PqyJPage()),
  PrototypeEntry('6EyhbjTAFK_', 'Facebook解除绑定 (1)', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/账号关联/Facebook绑定/解绑/Facebook解除绑定 (1)', 375, 667, (_) => P6EyhbjTAFKPage()),
  PrototypeEntry('WHlG1Lu7OA7', '绑定成功页面 (1)', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/账号关联/Facebook绑定/解绑/Facebook添加绑定 (1)/绑定成功页面 (1)', 375, 667, (_) => WHlG1Lu7OA7Page()),
  PrototypeEntry('GNiO-0M7VLj', 'Facebook添加绑定 (1)', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/账号关联/Facebook绑定/解绑/Facebook添加绑定 (1)', 375, 667, (_) => GNiO0M7VLjPage()),
  PrototypeEntry('2qmJIKDW-h-', 'Google+ 绑定成功页面', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/账号关联/Google+绑定/解绑/Google+添加绑定/Google+ 绑定成功页面', 375, 667, (_) => P2qmJIKDWhPage()),
  PrototypeEntry('OgYamrXEFal', 'Google+添加绑定', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/账号关联/Google+绑定/解绑/Google+添加绑定', 375, 667, (_) => OgYamrXEFalPage()),
  PrototypeEntry('unh8-xe9sQ2', 'Google+解除绑定', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/账号关联/Google+绑定/解绑/Google+解除绑定', 375, 667, (_) => unh8xe9sQ2Page()),
  PrototypeEntry('bEr-OmuCNPK', '账号日志详情', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/账号日志/账号日志详情', 375, 667, (_) => bErOmuCNPKPage()),
  PrototypeEntry('4KkPCCkJ3Of', '修改邮箱', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/邮箱/修改邮箱', 375, 667, (_) => P4KkPCCkJ3OfPage()),
  PrototypeEntry('NONO95E3FsC', '新绑定邮箱', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/邮箱/新绑定邮箱', 375, 667, (_) => NONO95E3FsCPage()),
  PrototypeEntry('Ar-QzgJ9bnH', '选择验证方式(修改邮箱)', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/邮箱/修改邮箱/选择验证方式(修改邮箱)', 375, 667, (_) => ArQzgJ9bnHPage()),
  PrototypeEntry('ts4SlmmlY-G', '邮箱修改成功', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/邮箱/修改邮箱/邮箱修改成功', 375, 667, (_) => ts4SlmmlYGPage()),
  PrototypeEntry('KQ-_vimYB7b', '邮箱验证 (修改手机号)', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/邮箱/修改邮箱/选择验证方式(修改邮箱)/邮箱验证 (修改手机号)', 375, 667, (_) => KQvimYB7bPage()),
  PrototypeEntry('ZbE9yFD85IH', '手机短信验证 (修改手机号)', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/邮箱/修改邮箱/选择验证方式(修改邮箱)/手机短信验证 (修改手机号)', 375, 667, (_) => ZbE9yFD85IHPage()),
  PrototypeEntry('Y8b-Vx2EPPp', '邮箱绑定成功', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/账号安全/邮箱/新绑定邮箱/邮箱绑定成功', 375, 667, (_) => Y8bVx2EPPpPage()),
  PrototypeEntry('r_zW38BO9Io', '邮箱绑定', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/邮箱绑定/邮箱绑定', 375, 667, (_) => rzW38BO9IoPage()),
  PrototypeEntry('Wpewew-m_lN', '输入验证码', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/邮箱绑定/邮箱绑定/输入验证码', 375, 667, (_) => WpewewmlNPage()),
  PrototypeEntry('pCkgNT8XRkc', '邮箱绑定成功页面', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)/邮箱绑定/邮箱绑定/邮箱绑定成功页面', 375, 667, (_) => pCkgNT8XRkcPage()),
  PrototypeEntry('E1Oa0Pvm6BO', '(APP)用户个人中心 (1)', '租户-APP端/APP/H5-个人中心/(APP)用户个人中心 (1)', 375, 667, (_) => E1Oa0Pvm6BOPage()),
  PrototypeEntry('SUfHkojkaR0', 'APP/H5-个人中心', '租户-APP端/APP/H5-个人中心', 375, 667, (_) => SUfHkojkaR0Page()),
  PrototypeEntry('k-H54yzCd', '协议勾选弹窗', '租户-APP端/协议勾选弹窗', 962, 1080, (_) => kH54yzCdPage()),
  PrototypeEntry('n-J1cwHfp', '选择手机号归属地', '租户-APP端/选择手机号归属地', 535, 1080, (_) => nJ1cwHfpPage()),
  PrototypeEntry('0jIS_efDdcn', '本机号码一键验证登入', '租户-APP端/会员端登录(APP)/本机号码一键验证登入', 375, 667, (_) => P0jISefDdcnPage()),
  PrototypeEntry('KIdMBIJQC2m', 'APP登录时检测到账号被冻结(弹窗)', '租户-APP端/会员端登录(APP)/APP登录时检测到账号被冻结(弹窗)', 375, 667, (_) => KIdMBIJQC2mPage()),
  PrototypeEntry('cnulI2qsvBQ', 'APP登录方式选择', '租户-APP端/会员端登录(APP)/APP登录方式选择', 971, 870, (_) => cnulI2qsvBQPage()),
  PrototypeEntry('qy6xv_44nUE', '邮箱验证码登录', '租户-APP端/会员端登录(APP)/邮箱验证码登录', 375, 667, (_) => qy6xv44nUEPage()),
  PrototypeEntry('wI65ZFSpGqI', '手机验证码登录', '租户-APP端/会员端登录(APP)/手机验证码登录', 375, 667, (_) => wI65ZFSpGqIPage()),
  PrototypeEntry('8oko0Gu4Nx3', '输入手机登录验证码', '租户-APP端/会员端登录(APP)/手机验证码登录/输入手机登录验证码', 375, 667, (_) => P8oko0Gu4Nx3Page()),
  PrototypeEntry('d4kpcMYob7u', '检测到手机号未注册', '租户-APP端/会员端登录(APP)/手机验证码登录/检测到手机号未注册', 375, 667, (_) => d4kpcMYob7uPage()),
  PrototypeEntry('i944FAsAeup', '输入邮件登录验证码', '租户-APP端/会员端登录(APP)/邮箱验证码登录/输入邮件登录验证码', 375, 667, (_) => i944FAsAeupPage()),
  PrototypeEntry('VJ0tDnmXUEu', 'APP切换登录页面', '租户-APP端/切换账户登录(APP)/APP切换登录页面', 375, 667, (_) => VJ0tDnmXUEuPage()),
  PrototypeEntry('VzWiUuGsAQ-', 'APP从设备移除账户', '租户-APP端/切换账户登录(APP)/APP从设备移除账户', 375, 667, (_) => VzWiUuGsAQPage()),
  PrototypeEntry('cRF08PB7kEe', 'APP移除密码', '租户-APP端/切换账户登录(APP)/APP移除密码', 375, 667, (_) => cRF08PB7kEePage()),
  PrototypeEntry('6azDWvwqLZJ', '密码修改成功页面', '租户-APP端/终端用户找回密码(APP)/密码修改成功页面', 375, 667, (_) => P6azDWvwqLZJPage()),
  PrototypeEntry('7uwTz_U6aN7', '查找账号-账号存在 (已绑定身份验证方式)', '租户-APP端/终端用户找回密码(APP)/查找账号-账号存在 (已绑定身份验证方式)', 375, 667, (_) => P7uwTzU6aN7Page()),
  PrototypeEntry('Zx1sq-Na6W6', '设置新密码', '租户-APP端/终端用户找回密码(APP)/设置新密码', 992, 802, (_) => Zx1sqNa6W6Page()),
  PrototypeEntry('2XEQbZ0HU_v', '手机号注册（默认）', '租户-APP端/终端用户注册(APP)/手机号注册（默认）', 375, 667, (_) => P2XEQbZ0HUvPage()),
  PrototypeEntry('CmmEnp49pEH', 'APP注册时检测到账号被冻结(弹窗)', '租户-APP端/终端用户注册(APP)/APP注册时检测到账号被冻结(弹窗)', 375, 667, (_) => CmmEnp49pEHPage()),
  PrototypeEntry('J7Ygf3v9_XN', '注册成功页面', '租户-APP端/终端用户注册(APP)/注册成功页面', 375, 667, (_) => J7Ygf3v9XNPage()),
  PrototypeEntry('gnNEa-mfuNT', '设置登录密码', '租户-APP端/终端用户注册(APP)/设置登录密码', 375, 667, (_) => gnNEamfuNTPage()),
  PrototypeEntry('-kGHial-Pge', '输入手机注册验证码', '租户-APP端/终端用户注册(APP)/手机号注册（默认）/输入手机注册验证码', 375, 667, (_) => kGHialPgePage()),
  PrototypeEntry('dC-sxuk_oWP', '登录授权页面（账号登录状态）', '租户-APP端/终端用户注册(APP)/第三方授权注册/登录授权页面（账号登录状态）', 375, 667, (_) => dCsxukoWPPage()),
  PrototypeEntry('n7GYOc85noR', '第三方登录页面（账号未登录状态）', '租户-APP端/终端用户注册(APP)/第三方授权注册/第三方登录页面（账号未登录状态）', 375, 667, (_) => n7GYOc85noRPage()),
  PrototypeEntry('2STTxfsewDx', '输入邮件注册验证码', '租户-APP端/终端用户注册(APP)/邮箱注册(未输入邮箱)/输入邮件注册验证码', 375, 667, (_) => P2STTxfsewDxPage()),
  PrototypeEntry('Fokfbeivniz', 'APP选择(站点)国家&地区-页面', '租户-PC端/注册 登录 找回密码 切换账号/站点切换登录(未设计)/APP/H5/APP选择(站点)国家&地区-页面', 375, 667, (_) => FokfbeivnizPage()),
  PrototypeEntry('TUst4HcH0iL', 'APP选择(站点)国家&地区-弹窗', '租户-PC端/注册 登录 找回密码 切换账号/站点切换登录(未设计)/APP/H5/APP选择(站点)国家&地区-弹窗', 375, 667, (_) => TUst4HcH0iLPage()),
];

final Map<String, PrototypeEntry> prototypePageById = {
  for (final e in prototypePages) e.id: e,
};
